import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  page: {
    padding: "24px",
    color: "var(--color-text-primary)",
    background: "var(--color-surface-muted)",
    minHeight: "100vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "18px",
    "& h1": {
      margin: [0, 0, 6, 0],
      fontSize: "26px",
      lineHeight: "32px",
    },
    "& p": {
      margin: 0,
      color: "var(--color-text-muted)",
      fontSize: "14px",
      lineHeight: "20px",
      maxWidth: "760px",
    },
  },
  actions: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
  },
  button: {
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    padding: "9px 13px",
    background: "var(--color-white)",
    color: "var(--color-text-primary)",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    minHeight: "38px",
    boxShadow: "0 3px 8px rgba(15, 23, 42, 0.08)",
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.55,
    },
  },
  primaryButton: {
    border: "none",
    background: "var(--color-primary)",
    color: "var(--color-white)",
  },
  dangerButton: {
    border: "none",
    background: "#EF5B5B",
    color: "var(--color-white)",
  },
  metrics: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "12px",
    marginBottom: "18px",
  },
  metric: {
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    padding: "12px",
    background: "var(--color-white)",
    boxShadow: "0 12px 26px rgba(15, 23, 42, 0.08)",
    "& span": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: "12px",
      marginBottom: "5px",
    },
    "& strong": {
      fontSize: "20px",
      lineHeight: "26px",
    },
  },
  filterPanel: {
    display: "grid",
    gridTemplateColumns: "minmax(150px, 0.8fr) repeat(4, minmax(150px, 1fr)) minmax(260px, 1.4fr) auto",
    gap: "10px",
    alignItems: "center",
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    background: "var(--color-white)",
    padding: "12px",
    marginBottom: "10px",
    boxShadow: "0 12px 26px rgba(15, 23, 42, 0.08)",
    "@media (max-width: 1300px)": {
      gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    },
    "@media (max-width: 760px)": {
      gridTemplateColumns: "1fr",
    },
    "& select, & input[type='text'], & input:not([type])": {
      width: "100%",
      minHeight: "38px",
      border: "1px solid var(--color-border)",
      borderRadius: "8px",
      background: "var(--color-white)",
      color: "var(--color-text-primary)",
      padding: "8px 10px",
      fontSize: "13px",
      boxSizing: "border-box",
      boxShadow: "inset 0 1px 2px rgba(15, 23, 42, 0.04)",
    },
  },
  toggleControl: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    minHeight: "38px",
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    background: "var(--color-surface-subtle)",
    padding: "8px 10px",
    color: "#445066",
    fontSize: "13px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    boxSizing: "border-box",
    "& input": {
      width: "16px",
      height: "16px",
      accentColor: "var(--color-primary)",
      flexShrink: 0,
    },
  },
  resultLine: {
    margin: [0, 0, 14, 0],
    color: "var(--color-text-muted)",
    fontSize: "13px",
    lineHeight: "18px",
    fontWeight: "var(--font-weight-semibold)",
  },
  group: {
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    padding: "18px",
    background: "var(--color-white)",
    marginBottom: "16px",
    boxShadow: "0 18px 42px rgba(15, 23, 42, 0.12)",
  },
  groupHead: {
    display: "flex",
    justifyContent: "space-between",
    gap: "14px",
    alignItems: "flex-start",
    flexWrap: "wrap",
    marginBottom: "14px",
    "& h2": {
      margin: 0,
      fontSize: "18px",
      lineHeight: "24px",
    },
    "& p": {
      margin: [4, 0, 0, 0],
      color: "var(--color-text-muted)",
      fontSize: "13px",
    },
  },
  tagRow: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    marginTop: "8px",
  },
  tag: {
    borderRadius: "999px",
    background: "#F2F5F8",
    color: "#445066",
    padding: "5px 8px",
    fontSize: "12px",
    lineHeight: "16px",
  },
  statusTag: {
    borderRadius: "999px",
    background: "rgba(4, 165, 132, 0.12)",
    color: "#04745E",
    padding: "5px 8px",
    fontSize: "12px",
    fontWeight: "var(--font-weight-semibold)",
  },
  warningTag: {
    background: "rgba(245, 165, 36, 0.14)",
    color: "#A66600",
  },
  flow: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(180px, 1fr))",
    gap: "12px",
    marginBottom: "14px",
    "@media (max-width: 1100px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
    },
  },
  flowCard: {
    border: "1px solid #E1E7EF",
    borderRadius: "8px",
    background: "linear-gradient(180deg, var(--color-white) 0%, var(--color-surface-subtle) 100%)",
    padding: "12px",
    boxShadow: "0 10px 22px rgba(15, 23, 42, 0.08)",
    "& span": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: "11px",
      lineHeight: "15px",
      fontWeight: "var(--font-weight-semibold)",
      textTransform: "uppercase",
      marginBottom: "5px",
    },
    "& strong": {
      display: "block",
      fontSize: "15px",
      lineHeight: "20px",
      overflowWrap: "anywhere",
    },
    "& small": {
      display: "block",
      color: "#445066",
      fontSize: "12px",
      lineHeight: "17px",
      marginTop: "5px",
      overflowWrap: "anywhere",
    },
  },
  marketLink: {
    display: "inline-flex",
    alignItems: "center",
    color: "#2548B8",
    fontSize: "15px",
    lineHeight: "20px",
    fontWeight: "var(--font-weight-semibold)",
    textDecoration: "none",
    overflowWrap: "anywhere",
    "&:hover": {
      textDecoration: "underline",
    },
  },
  sourceChipList: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap",
  },
  sourceChip: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "24px",
    borderRadius: "999px",
    border: "1px solid rgba(4, 165, 132, 0.24)",
    background: "var(--color-primary-soft)",
    color: "#04745E",
    padding: "4px 9px",
    fontSize: "13px",
    lineHeight: "16px",
    fontWeight: "var(--font-weight-semibold)",
    textDecoration: "none",
    overflowWrap: "anywhere",
    boxShadow: "0 5px 12px var(--color-primary-soft)",
    "&:hover": {
      background: "rgba(4, 165, 132, 0.14)",
      borderColor: "rgba(4, 165, 132, 0.42)",
    },
  },
  sourceChipEmpty: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "24px",
    color: "#445066",
    fontSize: "13px",
    lineHeight: "16px",
    fontWeight: "var(--font-weight-semibold)",
  },
  columns: {
    display: "grid",
    gridTemplateColumns: "minmax(260px, 1.1fr) minmax(260px, 1fr)",
    gap: "14px",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr",
    },
  },
  section: {
    border: "1px solid #EEF2F6",
    borderRadius: "8px",
    padding: "12px",
    background: "#FCFDFE",
    boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.8)",
    "& h3": {
      margin: [0, 0, 10, 0],
      fontSize: "14px",
      lineHeight: "20px",
    },
  },
  sectionNotice: {
    margin: [0, 0, 8, 0],
    color: "#445066",
    fontSize: "12px",
    lineHeight: "16px",
    border: "1px solid #F2C94C33",
    background: "#FFF7E0",
    borderRadius: "6px",
    padding: "7px 8px",
  },
  sourceOption: {
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    background: "var(--color-white)",
    padding: "10px",
    marginBottom: "10px",
    boxShadow: "0 8px 18px rgba(15, 23, 42, 0.08)",
    transition: "border-color 120ms ease, box-shadow 120ms ease, transform 120ms ease",
    "& label": {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      fontWeight: "var(--font-weight-semibold)",
      fontSize: "14px",
    },
    "& input": {
      width: "16px",
      height: "16px",
      accentColor: "var(--color-primary)",
      flexShrink: 0,
    },
    "& p": {
      margin: [7, 0, 0, 24],
      color: "var(--color-text-muted)",
      fontSize: "12px",
      lineHeight: "17px",
    },
  },
  sourceSelected: {
    borderColor: "var(--color-primary)",
    boxShadow: "0 12px 24px rgba(4, 165, 132, 0.18)",
    transform: "translateY(-1px)",
  },
  sourceDisabled: {
    opacity: 0.66,
    borderColor: "var(--color-border)",
    background: "var(--color-surface-subtle)",
    boxShadow: "0 5px 12px rgba(15, 23, 42, 0.05)",
  },
  sourceTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "10px",
    flexWrap: "wrap",
    "& strong": {
      fontSize: "14px",
      lineHeight: "19px",
      overflowWrap: "anywhere",
    },
  },
  roleBadge: {
    borderRadius: "999px",
    background: "rgba(67, 103, 246, 0.1)",
    color: "#2548B8",
    padding: "4px 8px",
    fontSize: "11px",
    lineHeight: "14px",
    fontWeight: "var(--font-weight-semibold)",
    whiteSpace: "nowrap",
  },
  useToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: "7px",
    marginTop: "8px",
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    background: "var(--color-surface-subtle)",
    padding: "7px 8px",
    color: "#445066",
    fontSize: "12px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    "& input": {
      width: "15px",
      height: "15px",
      accentColor: "var(--color-primary)",
    },
    "& span": {
      lineHeight: "16px",
    },
  },
  sourceMeta: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: "6px",
    marginTop: "8px",
    color: "#445066",
    fontSize: "12px",
  },
  links: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap",
    marginTop: "8px",
    "& a": {
      color: "#04745E",
      fontSize: "12px",
      textDecoration: "none",
      background: "var(--color-primary-soft)",
      borderRadius: "999px",
      padding: "4px 7px",
    },
  },
  relationNote: {
    display: "flex",
    flexDirection: "column",
    gap: "3px",
    marginTop: "8px",
    border: "1px solid #EEF2F6",
    borderRadius: "8px",
    background: "var(--color-surface-subtle)",
    padding: "8px",
    color: "#445066",
    fontSize: "12px",
    lineHeight: "17px",
    overflowWrap: "anywhere",
  },
  decisionPanel: {
    marginTop: "14px",
    borderTop: "1px solid #EEF2F6",
    paddingTop: "14px",
    display: "grid",
    gridTemplateColumns: "minmax(220px, 0.8fr) minmax(260px, 1fr) auto",
    gap: "12px",
    alignItems: "end",
    "@media (max-width: 1100px)": {
      gridTemplateColumns: "1fr",
    },
  },
  actionPreview: {
    border: "1px solid rgba(4, 165, 132, 0.22)",
    borderRadius: "8px",
    background: "rgba(4, 165, 132, 0.07)",
    padding: "10px 12px",
    color: "#04745E",
    boxShadow: "0 8px 18px rgba(4, 165, 132, 0.12)",
    "& strong": {
      display: "block",
      fontSize: "13px",
      lineHeight: "18px",
      marginBottom: "4px",
    },
    "& span": {
      display: "block",
      fontSize: "12px",
      lineHeight: "17px",
    },
  },
  note: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    color: "#445066",
    fontSize: "13px",
    fontWeight: "var(--font-weight-semibold)",
    "& textarea": {
      minHeight: "72px",
      resize: "vertical",
      border: "1px solid var(--color-border)",
      borderRadius: "8px",
      padding: "10px 12px",
      color: "var(--color-text-primary)",
      fontSize: "14px",
      lineHeight: "19px",
    },
  },
  empty: {
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    background: "var(--color-white)",
    padding: "18px",
    color: "var(--color-text-muted)",
    boxShadow: "0 12px 26px rgba(15, 23, 42, 0.08)",
  },
});
