import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  page: {
    padding: "28px 32px 64px",
    width: "100%",
    boxSizing: "border-box",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    marginBottom: 24,
    flexWrap: "wrap",
    "& h1": {
      margin: 0,
      fontSize: 26,
      fontWeight: "var(--font-weight-bold)",
      color: "var(--color-text-primary)",
    },
    "& p": {
      margin: "6px 0 0",
      color: "var(--color-text-secondary, #6b7787)",
      fontSize: 14,
      maxWidth: 640,
    },
  },
  badgeRow: { display: "flex", gap: 10, flexWrap: "wrap" },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 12px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 600,
    background: "#EEF2F7",
    color: "#41506A",
  },
  badgeOk: { background: "rgba(0,192,153,0.14)", color: "#0F9D82" },
  badgeWarn: { background: "rgba(240,169,45,0.16)", color: "#B77400" },
  badgeErr: { background: "rgba(226,84,84,0.14)", color: "#C0392B" },
  tabs: {
    display: "flex",
    gap: 4,
    flexWrap: "wrap",
    marginBottom: 22,
    borderBottom: "1px solid #E6EAF0",
    paddingBottom: 0,
  },
  tab: {
    border: "none",
    background: "transparent",
    padding: "10px 16px",
    borderRadius: 0,
    fontSize: 13.5,
    fontWeight: 700,
    color: "#64748B",
    cursor: "pointer",
    borderBottom: "2px solid transparent",
    marginBottom: -1,
    transition: "color 0.16s ease, border-color 0.16s ease",
    "&:hover": { color: "#4F46E5" },
  },
  tabActive: {
    background: "transparent",
    color: "#4F46E5",
    borderBottom: "2px solid #4F46E5",
    "&:hover": { background: "transparent", color: "#4F46E5" },
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.35fr) minmax(0, 1fr)",
    gap: 22,
    "@media (max-width: 1024px)": { gridTemplateColumns: "1fr" },
  },
  card: {
    background: "var(--color-white, #fff)",
    border: "1px solid #E4EAF1",
    borderRadius: 16,
    padding: 22,
    boxShadow: "0 1px 2px rgba(16,24,40,0.04)",
  },
  cardHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    gap: 12,
    "& h2": { margin: 0, fontSize: 17, fontWeight: 700, color: "var(--color-text-primary)" },
    "& h3": { margin: 0, fontSize: 14, fontWeight: 700, color: "var(--color-text-primary)" },
    "& p": { margin: "4px 0 0", fontSize: 12.5, color: "#7A879A" },
  },
  section: { marginTop: 18 },
  sectionTitle: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: 13,
    fontWeight: 700,
    color: "#41506A",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    margin: "0 0 10px",
  },
  fieldRow: {
    display: "grid",
    gridTemplateColumns: "1fr 116px",
    alignItems: "center",
    gap: 12,
    padding: "7px 0",
    borderBottom: "1px dashed #EDF1F6",
    "& code": {
      fontSize: 12.5,
      color: "#41506A",
      fontFamily: "'Source Code Pro', monospace",
    },
    "& small": { display: "block", color: "#9AA6B6", fontSize: 11, marginTop: 2 },
  },
  input: {
    width: "100%",
    height: 38,
    border: "1px solid #D8E1EB",
    borderRadius: 8,
    padding: "8px 11px",
    boxSizing: "border-box",
    fontSize: 13,
    outline: "none",
    "&:focus": {
      borderColor: "var(--color-primary, #00C099)",
      boxShadow: "0 0 0 3px rgba(0,192,153,0.12)",
    },
  },
  selectField: {
    appearance: "none",
    WebkitAppearance: "none",
    MozAppearance: "none",
    cursor: "pointer",
    minWidth: 210,
    paddingRight: 30,
    backgroundColor: "#fff",
    backgroundImage:
      "url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%237A879A' stroke-width='2.4' stroke-linecap='round' stroke-linejoin='round'><polyline points='6 9 12 15 18 9'/></svg>\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 10px center",
  },

  subNav: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    marginBottom: 18,
    borderBottom: "1px solid #E7EDF3",
    paddingBottom: 0,
  },
  subTab: {
    border: "none",
    background: "transparent",
    color: "#6B7789",
    fontSize: 13.5,
    fontWeight: 600,
    padding: "10px 14px",
    cursor: "pointer",
    borderBottom: "2px solid transparent",
    marginBottom: -1,
    transition: "color 160ms ease, border-color 160ms ease",
    "&:hover": { color: "#2B3648" },
  },
  subTabActive: {
    color: "#4F46E5",
    borderBottomColor: "#4F46E5",
  },
  refCtxBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    border: "1px dashed #CBD5E1",
    background: "#F7FAFC",
    color: "#41506A",
    borderRadius: 10,
    padding: "10px 14px",
    fontSize: 13,
    cursor: "pointer",
    marginBottom: 14,
    transition: "border-color 160ms ease, background-color 160ms ease",
    "&:hover": { borderColor: "var(--color-primary, #00C099)", background: "#F0FBF8" },
  },
  refCtxMeta: { color: "#8592A4", fontSize: 12 },
  drawerOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(20,30,55,0.34)",
    backdropFilter: "blur(2px)",
    zIndex: 3500,
    display: "flex",
    justifyContent: "flex-end",
    animation: "$fadeIn 160ms ease",
  },
  "@keyframes fadeIn": { from: { opacity: 0 }, to: { opacity: 1 } },
  drawerPanel: {
    width: "min(720px, 96vw)",
    height: "100%",
    background: "#fff",
    boxShadow: "-16px 0 40px rgba(20,30,55,0.18)",
    display: "flex",
    flexDirection: "column",
    animation: "$slideIn 200ms ease",
  },
  "@keyframes slideIn": { from: { transform: "translateX(24px)", opacity: 0.6 }, to: { transform: "translateX(0)", opacity: 1 } },
  drawerHead: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    padding: "20px 22px",
    borderBottom: "1px solid #E7EDF3",
  },
  drawerBody: { padding: "18px 22px", overflowY: "auto", flex: 1 },


  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
    marginTop: 4,
  },
  formField: { display: "flex", flexDirection: "column", gap: 6, minWidth: 0 },
  formLabel: { fontSize: 12.5, fontWeight: 600, color: "#41506A" },
  fieldHelp: { fontSize: 11, color: "#9AA6B6", lineHeight: "15px" },
  switchRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "#41506A",
    "& input": { width: 16, height: 16, cursor: "pointer" },
  },
  chipRow: { display: "flex", flexWrap: "wrap", gap: 8 },
  chip: {
    border: "1px solid #D8E1EB",
    background: "#fff",
    color: "#41506A",
    borderRadius: 999,
    padding: "5px 12px",
    fontSize: 12.5,
    cursor: "pointer",
    transition: "background-color 180ms ease, border-color 180ms ease, color 180ms ease",
    "&:hover": { borderColor: "var(--color-primary, #00C099)" },
  },
  chipActive: {
    background: "rgba(0,192,153,0.12)",
    borderColor: "var(--color-primary, #00C099)",
    color: "#017a63",
    fontWeight: 600,
  },
  filterBar: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
    gap: 10,
    marginBottom: 14,
  },
  clickRow: { cursor: "pointer", "&:hover": { background: "#F5F8FB" } },
  kvGrid: {
    display: "grid",
    gridTemplateColumns: "160px 1fr",
    gap: "6px 12px",
    fontSize: 13,
    "& dt": { color: "#7A879A" },
    "& dd": { margin: 0, color: "#2B3648", wordBreak: "break-all" },
  },
  pager: { display: "flex", alignItems: "center", gap: 12, marginTop: 12, fontSize: 13, color: "#41506A" },


  textarea: {
    width: "100%",
    minHeight: 190,
    border: "1px solid #D8E1EB",
    borderRadius: 10,
    padding: "11px 13px",
    boxSizing: "border-box",
    fontFamily: "'Source Code Pro', monospace",
    fontSize: 12.5,
    lineHeight: "18px",
    outline: "none",
    resize: "vertical",
    "&:focus": { borderColor: "var(--color-primary, #00C099)" },
  },
  toggle: { display: "inline-flex", alignItems: "center", gap: 8, cursor: "pointer", fontSize: 13, fontWeight: 600, color: "#41506A" },
  btnRow: { display: "flex", gap: 10, flexWrap: "wrap", marginTop: 18 },
  btn: {
    border: "none",
    borderRadius: 10,
    padding: "10px 18px",
    fontSize: 13.5,
    fontWeight: 600,
    cursor: "pointer",
    transition: "opacity 0.16s ease, background 0.16s ease",
    "&:disabled": { opacity: 0.5, cursor: "not-allowed" },
  },
  btnPrimary: { background: "var(--color-primary, #00C099)", color: "#fff" },
  btnGhost: { background: "#EEF2F7", color: "#41506A" },
  previewScore: {
    display: "flex",
    alignItems: "baseline",
    gap: 12,
    margin: "6px 0 14px",
  },
  previewValue: { fontSize: 40, fontWeight: 800, color: "var(--color-primary, #00C099)", lineHeight: 1 },
  previewLevel: { fontSize: 15, fontWeight: 700, color: "#41506A" },
  breakdownTable: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 12.5,
    "& th": {
      textAlign: "left",
      color: "#8592A4",
      fontWeight: 600,
      padding: "6px 8px",
      borderBottom: "1px solid #EAEFF5",
    },
    "& td": { padding: "6px 8px", borderBottom: "1px solid #F2F5F9", color: "#3A4759" },
    "& td:last-child, & th:last-child": { textAlign: "right" },
  },
  subRow: {
    background: "#FAFCFF",
    "& td": {
      padding: "4px 8px 4px 22px",
      color: "#5A6B82",
      fontSize: 11.5,
      borderBottom: "1px dashed #EEF3F9",
    },
  },
  subPenalty: { color: "#C0392B !important" },
  srcBadge: {
    display: "inline-block",
    marginLeft: 8,
    padding: "1px 7px",
    borderRadius: 999,
    fontSize: 10,
    fontWeight: 700,
    verticalAlign: "middle",
  },
  srcDerived: { background: "rgba(46,164,110,0.14)", color: "#1E8A55" },
  srcManual: { background: "rgba(214,158,46,0.16)", color: "#9A6B08" },
  srcMissing: { background: "#EEF2F7", color: "#8592A4" },
  srcMock: { background: "rgba(90,103,124,0.14)", color: "#5A677C" },
  srcStale: { background: "rgba(221,107,32,0.16)", color: "#C05621" },
  provLegend: { display: "flex", flexWrap: "wrap", gap: 8, margin: "10px 0" },
  provPanel: {
    marginTop: 12,
    padding: 12,
    borderRadius: 10,
    background: "#F7F9FC",
    border: "1px solid #E4EAF2",
  },
  refToolbar: { display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center", marginBottom: 12 },
  refTable: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 13,
    "& th": { textAlign: "left", padding: "8px 10px", color: "#7A879A", borderBottom: "1px solid #E4EAF2", fontWeight: 600 },
    "& td": { padding: "8px 10px", borderBottom: "1px solid #EEF2F7", verticalAlign: "top" },
  },
  subToggle: {
    cursor: "pointer",
    color: "#2EA46E",
    fontSize: 11,
    fontWeight: 600,
    marginLeft: 8,
    userSelect: "none",
  },
  advancedArea: {
    width: "100%",
    minHeight: 160,
    fontFamily: "monospace",
    fontSize: 12,
    lineHeight: "17px",
    color: "#D7E3F4",
    background: "#0B1220",
    border: "1px solid #23304A",
    borderRadius: 10,
    padding: 12,
    marginTop: 6,
    resize: "vertical",
    boxSizing: "border-box",
    "&::placeholder": { color: "#5E6C86" },
  },
  pill: {
    display: "inline-block",
    padding: "3px 9px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 600,
    marginRight: 6,
    marginBottom: 6,
  },
  pillErr: { background: "rgba(226,84,84,0.12)", color: "#C0392B" },
  pillMuted: { background: "#EEF2F7", color: "#5A6B82" },
  runtimeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: 10,
    margin: "12px 0",
    "& dt": { fontSize: 11, color: "#8592A4", fontWeight: 600, textTransform: "uppercase" },
    "& dd": { margin: "3px 0 0", fontSize: 13, color: "#3A4759", fontWeight: 600 },
  },
  errorText: { color: "#C0392B", fontSize: 12.5, marginTop: 8 },
  stateBox: { padding: 40, textAlign: "center", color: "#7A879A" },
  idInput: { display: "flex", gap: 8, marginTop: 10 },
  groupBlock: {
    border: "1px solid #EEF2F7",
    borderRadius: 12,
    padding: "12px 14px",
    marginBottom: 12,
    background: "#FBFCFE",
  },
  groupTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "#41506A",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    margin: "0 0 8px",
  },
  collapsible: { marginTop: 16, borderTop: "1px dashed #E4EAF1", paddingTop: 12 },
  collapsibleHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    fontSize: 12.5,
    fontWeight: 600,
    color: "#7A879A",
    userSelect: "none",
  },
  pre: {
    background: "#0F1626",
    color: "#C7D2E0",
    borderRadius: 10,
    padding: 12,
    fontSize: 11.5,
    lineHeight: "17px",
    overflowX: "auto",
    marginTop: 10,
    fontFamily: "'Source Code Pro', monospace",
    maxHeight: 260,
  },
  rankLegend: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  rankChip: {
    fontSize: 11.5,
    fontWeight: 600,
    padding: "4px 9px",
    borderRadius: 999,
    background: "#EEF2F7",
    color: "#41506A",
  },
  thresholdRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr auto",
    gap: 8,
    alignItems: "center",
    marginBottom: 6,
  },
  smallBtn: {
    border: "1px solid #E4EAF1",
    background: "#fff",
    borderRadius: 8,
    width: 34,
    height: 34,
    cursor: "pointer",
    color: "#C0392B",
    fontWeight: 700,
    fontSize: 16,
  },
  addBtn: {
    border: "1px dashed #C7D2E0",
    background: "#fff",
    borderRadius: 8,
    padding: "7px 12px",
    fontSize: 12.5,
    fontWeight: 600,
    color: "#41506A",
    cursor: "pointer",
    marginTop: 4,
  },
  tradeSummary: {
    display: "flex",
    gap: 16,
    flexWrap: "wrap",
    margin: "6px 0 14px",
  },
  tradeStat: {
    background: "#F6F9FC",
    border: "1px solid #EAEFF5",
    borderRadius: 12,
    padding: "10px 14px",
    minWidth: 110,
    "& span": { display: "block", fontSize: 11, color: "#8592A4", fontWeight: 600 },
    "& strong": { fontSize: 22, color: "#1F2A3C" },
  },

  /* ---- sub-formula (formula-inside-formula) editor ---- */
  sfIntro: {
    fontSize: 12.5,
    color: "#6b7787",
    lineHeight: "18px",
    margin: "2px 0 14px",
  },
  sfCard: {
    border: "1px solid #E7EDF4",
    borderRadius: 14,
    marginBottom: 12,
    background: "#FFFFFF",
    overflow: "hidden",
  },
  sfHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: "12px 14px",
    cursor: "pointer",
    userSelect: "none",
    background: "#FAFCFE",
    "&:hover": { background: "#F4F8FC" },
  },
  sfHeadLeft: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  sfTitle: { fontSize: 14, fontWeight: 700, color: "#1F2A3C" },
  sfKindBadge: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "#5B6B82",
    background: "#EEF3F9",
    borderRadius: 6,
    padding: "2px 7px",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  sfBody: { padding: "6px 14px 16px", borderTop: "1px solid #EEF3F8" },
  sfFormula: {
    fontSize: 12.5,
    color: "#33465F",
    background: "#F6F9FC",
    border: "1px solid #EAEFF5",
    borderRadius: 10,
    padding: "8px 12px",
    margin: "10px 0",
    fontFamily: "monospace",
    lineHeight: "18px",
    wordBreak: "break-word",
  },
  sfSource: { fontSize: 12, color: "#7A879A", margin: "4px 0 8px", "& b": { color: "#5B6B82" } },
  sfSubRow: {
    display: "grid",
    gridTemplateColumns: "1fr 96px 120px",
    alignItems: "center",
    gap: 10,
    padding: "6px 0",
    borderBottom: "1px dashed #EEF2F7",
    "& small": { display: "block", fontSize: 10.5, color: "#93A0B2" },
  },
  sfSubLabel: { fontSize: 13, color: "#2A3C57", fontWeight: 600 },
  normBadge: {
    fontSize: 10,
    color: "#5B6B82",
    background: "#EEF3F9",
    borderRadius: 6,
    padding: "1px 6px",
    marginLeft: 6,
    fontWeight: 700,
  },
  penaltyTag: {
    fontSize: 10,
    color: "#B4232A",
    background: "#FDEDED",
    borderRadius: 6,
    padding: "1px 6px",
    marginLeft: 6,
    fontWeight: 700,
  },
  /* tooltip / help */
  helpWrap: { position: "relative", display: "inline-flex" },
  helpIcon: {
    width: 16,
    height: 16,
    borderRadius: "50%",
    border: "1px solid #B9C6D6",
    color: "#5B6B82",
    fontSize: 11,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    background: "#fff",
    lineHeight: 1,
  },
  helpPop: {
    position: "absolute",
    zIndex: 40,
    top: "22px",
    left: 0,
    width: 300,
    background: "#1F2A3C",
    color: "#EAF0F7",
    borderRadius: 10,
    padding: "12px 14px",
    boxShadow: "0 10px 30px rgba(20,30,50,0.28)",
    fontSize: 12,
    lineHeight: "17px",
    "& b": { color: "#fff", display: "block", marginBottom: 4 },
    "& em": { color: "#A9B7CA", fontStyle: "normal" },
    "& code": { color: "#8FE3C2", fontFamily: "monospace" },
  },
  helpRow: { marginTop: 6 },
});
