import { createUseStyles } from 'react-jss';

export const useStyles = createUseStyles({
  page: {
    minHeight: '100vh',
    padding: '28px 32px 60px',
    background: 'var(--color-surface-subtle)',
  },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 24,
    marginBottom: 22,
  },
  eyebrow: {
    marginBottom: 6,
    color: 'var(--color-primary-dark)',
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  title: {
    fontSize: 30,
    lineHeight: '36px',
    fontWeight: 700,
  },
  subtitle: {
    maxWidth: 720,
    marginTop: 8,
    color: 'var(--color-text-muted)',
    fontSize: 14,
    lineHeight: '21px',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  networkCard: {
    minWidth: 230,
    padding: '10px 13px',
    border: '1px solid var(--color-border)',
    borderRadius: 10,
    background: 'var(--color-white)',
    fontSize: 12,
    lineHeight: '18px',
  },
  networkTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    fontWeight: 700,
  },
  networkDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: 'var(--color-primary)',
  },
  address: {
    color: 'var(--color-text-muted)',
    fontFamily: 'monospace',
    overflowWrap: 'anywhere',
  },
  tabs: {
    display: 'flex',
    gap: 4,
    width: 'fit-content',
    marginBottom: 20,
    padding: 4,
    border: '1px solid var(--color-border)',
    borderRadius: 10,
    background: 'var(--color-white)',
  },
  tab: {
    minWidth: 128,
    padding: '10px 16px',
    border: 0,
    borderRadius: 7,
    background: 'transparent',
    color: 'var(--color-text-secondary)',
    fontSize: 14,
    fontWeight: 600,
  },
  activeTab: {
    background: 'var(--color-primary)',
    color: 'var(--color-white)',
  },
  notice: {
    marginBottom: 18,
    padding: '12px 14px',
    border: '1px solid rgba(32, 130, 234, 0.22)',
    borderRadius: 9,
    background: 'var(--color-info-soft)',
    color: 'var(--color-text-secondary)',
    fontSize: 13,
    lineHeight: '19px',
  },
  warning: {
    borderColor: 'rgba(255, 199, 2, 0.45)',
    background: 'var(--color-warning-soft)',
  },
  createLayout: {
    display: 'grid',
    gridTemplateColumns: 'minmax(290px, 360px) minmax(520px, 1fr)',
    gap: 18,
    alignItems: 'start',
  },
  poolsLayout: {
    display: 'grid',
    gridTemplateColumns: 'minmax(420px, 1.2fr) minmax(390px, 0.8fr)',
    gap: 18,
    alignItems: 'start',
  },
  panel: {
    border: '1px solid var(--color-border)',
    borderRadius: 12,
    background: 'var(--color-white)',
    boxShadow: 'var(--shadow-soft)',
    overflow: 'hidden',
  },
  stickyPanel: {
    position: 'sticky',
    top: 20,
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    padding: '16px 18px',
    borderBottom: '1px solid var(--color-border-subtle)',
  },
  panelTitle: {
    fontSize: 17,
    lineHeight: '22px',
    fontWeight: 700,
  },
  panelHint: {
    marginTop: 4,
    color: 'var(--color-text-muted)',
    fontSize: 12,
    lineHeight: '17px',
  },
  panelBody: {
    padding: 18,
  },
  modeToggle: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 4,
    marginBottom: 14,
    padding: 4,
    borderRadius: 9,
    background: 'var(--color-surface-muted)',
  },
  modeButton: {
    padding: '9px 8px',
    border: 0,
    borderRadius: 7,
    background: 'transparent',
    color: 'var(--color-text-muted)',
    fontSize: 13,
    fontWeight: 600,
  },
  activeMode: {
    background: 'var(--color-white)',
    color: 'var(--color-text-primary)',
    boxShadow: '0 1px 4px rgba(7, 11, 53, 0.10)',
  },
  search: {
    width: '100%',
    height: 42,
    marginBottom: 10,
    padding: '0 12px',
    border: '1px solid var(--color-border)',
    borderRadius: 8,
    background: 'var(--color-white)',
    fontSize: 14,
  },
  projectList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    maxHeight: 520,
    overflowY: 'auto',
  },
  projectCard: {
    display: 'grid',
    gridTemplateColumns: '42px 1fr auto',
    gap: 11,
    alignItems: 'center',
    width: '100%',
    padding: 11,
    border: '1px solid var(--color-border-subtle)',
    borderRadius: 9,
    background: 'var(--color-white)',
    textAlign: 'left',
    '&:hover': {
      borderColor: 'rgba(4, 165, 132, 0.45)',
      background: 'var(--color-primary-soft)',
    },
  },
  selectedProject: {
    borderColor: 'var(--color-primary)',
    background: 'var(--color-primary-soft)',
  },
  logo: {
    width: 42,
    height: 42,
    borderRadius: 10,
    objectFit: 'cover',
    background: 'var(--color-surface-muted)',
  },
  logoFallback: {
    display: 'grid',
    placeItems: 'center',
    width: 42,
    height: 42,
    borderRadius: 10,
    background: 'var(--color-primary-soft-strong)',
    color: 'var(--color-primary-dark)',
    fontWeight: 700,
  },
  projectName: {
    fontSize: 14,
    fontWeight: 700,
  },
  projectMeta: {
    marginTop: 3,
    color: 'var(--color-text-muted)',
    fontSize: 12,
  },
  check: {
    color: 'var(--color-primary)',
    fontSize: 18,
    fontWeight: 700,
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '15px 14px',
  },
  fullWidth: {
    gridColumn: '1 / -1',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    minWidth: 0,
  },
  label: {
    color: 'var(--color-text-secondary)',
    fontSize: 12,
    fontWeight: 700,
  },
  required: {
    color: 'var(--color-danger)',
  },
  input: {
    width: '100%',
    height: 42,
    padding: '0 12px',
    border: '1px solid var(--color-border)',
    borderRadius: 8,
    background: 'var(--color-white)',
    fontSize: 14,
    '&:focus': {
      borderColor: 'var(--color-primary)',
      boxShadow: '0 0 0 3px var(--color-primary-soft)',
    },
    '&:disabled': {
      background: 'var(--color-surface-muted)',
      color: 'var(--color-text-muted)',
    },
  },
  textarea: {
    minHeight: 92,
    padding: 12,
    resize: 'vertical',
  },
  helper: {
    color: 'var(--color-text-muted)',
    fontSize: 11,
    lineHeight: '15px',
  },
  sectionHeading: {
    gridColumn: '1 / -1',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginTop: 6,
    paddingTop: 16,
    borderTop: '1px solid var(--color-border-subtle)',
    fontSize: 14,
    fontWeight: 700,
  },
  formActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 20,
    paddingTop: 16,
    borderTop: '1px solid var(--color-border-subtle)',
  },
  button: {
    minHeight: 40,
    padding: '0 16px',
    border: 0,
    borderRadius: 8,
    background: 'var(--color-primary)',
    color: 'var(--color-white)',
    fontSize: 13,
    fontWeight: 700,
    '&:hover': {
      background: 'var(--color-primary-hover)',
    },
    '&:disabled': {
      cursor: 'not-allowed',
      opacity: 0.5,
    },
  },
  secondaryButton: {
    minHeight: 38,
    padding: '0 14px',
    border: '1px solid var(--color-border)',
    borderRadius: 8,
    background: 'var(--color-white)',
    color: 'var(--color-text-secondary)',
    fontSize: 13,
    fontWeight: 700,
    '&:hover': {
      borderColor: 'var(--color-primary)',
      color: 'var(--color-primary-dark)',
    },
    '&:disabled': {
      cursor: 'not-allowed',
      opacity: 0.5,
    },
  },
  dangerButton: {
    borderColor: 'rgba(255, 88, 88, 0.35)',
    color: 'var(--color-danger-dark)',
  },
  stepList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  step: {
    display: 'grid',
    gridTemplateColumns: '24px 1fr',
    gap: 9,
    alignItems: 'start',
    color: 'var(--color-text-muted)',
    fontSize: 12,
    lineHeight: '17px',
  },
  stepNumber: {
    display: 'grid',
    placeItems: 'center',
    width: 24,
    height: 24,
    borderRadius: '50%',
    background: 'var(--color-surface-muted)',
    fontWeight: 700,
  },
  activeStep: {
    color: 'var(--color-text-primary)',
    '& $stepNumber': {
      background: 'var(--color-primary)',
      color: 'var(--color-white)',
    },
  },
  doneStep: {
    color: 'var(--color-primary-dark)',
    '& $stepNumber': {
      background: 'var(--color-primary-soft-strong)',
      color: 'var(--color-primary-dark)',
    },
  },
  resultBox: {
    marginTop: 14,
    padding: 12,
    border: '1px solid var(--color-border)',
    borderRadius: 9,
    background: 'var(--color-surface-subtle)',
    fontSize: 12,
    lineHeight: '18px',
  },
  poolList: {
    display: 'flex',
    flexDirection: 'column',
  },
  poolRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(180px, 1.4fr) minmax(90px, 0.7fr) minmax(100px, 0.7fr) auto',
    gap: 12,
    alignItems: 'center',
    padding: '13px 16px',
    borderBottom: '1px solid var(--color-border-subtle)',
    cursor: 'pointer',
    '&:hover': {
      background: 'var(--color-surface-subtle)',
    },
  },
  selectedPool: {
    background: 'var(--color-primary-soft)',
  },
  status: {
    display: 'inline-flex',
    width: 'fit-content',
    padding: '4px 8px',
    borderRadius: 999,
    background: 'var(--color-surface-muted)',
    color: 'var(--color-text-secondary)',
    fontSize: 11,
    fontWeight: 700,
    textTransform: 'capitalize',
  },
  statusActive: {
    background: 'var(--color-primary-soft-strong)',
    color: 'var(--color-primary-dark)',
  },
  statusPending: {
    background: 'var(--color-warning-soft)',
    color: 'var(--color-warning-dark)',
  },
  statusFailed: {
    background: 'var(--color-danger-soft)',
    color: 'var(--color-danger-dark)',
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 10,
    marginBottom: 16,
  },
  detail: {
    padding: 10,
    borderRadius: 8,
    background: 'var(--color-surface-subtle)',
    fontSize: 12,
  },
  detailLabel: {
    marginBottom: 4,
    color: 'var(--color-text-muted)',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  operationCard: {
    marginTop: 12,
    paddingTop: 14,
    borderTop: '1px solid var(--color-border-subtle)',
  },
  operationTitle: {
    marginBottom: 9,
    fontSize: 13,
    fontWeight: 700,
  },
  operationFields: {
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    gap: 8,
    alignItems: 'end',
  },
  tripleOperationFields: {
    gridTemplateColumns: '1fr 90px auto',
  },
  placementEditor: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    minWidth: 0,
  },
  placementCard: {
    padding: 18,
    border: '1px solid var(--color-border)',
    borderRadius: 12,
    background: 'var(--color-white)',
    boxShadow: 'var(--shadow-soft)',
  },
  placementCardHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 16,
    paddingBottom: 14,
    borderBottom: '1px solid var(--color-border-subtle)',
  },
  placementTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 9,
    flexWrap: 'wrap',
  },
  placementPath: {
    marginTop: 4,
    color: 'var(--color-primary-dark)',
    fontFamily: 'monospace',
    fontSize: 12,
    fontWeight: 700,
  },
  bannerPreview: {
    width: 150,
    height: 76,
    flexShrink: 0,
    border: '1px solid var(--color-border-subtle)',
    borderRadius: 8,
    background: 'var(--color-surface-muted)',
    objectFit: 'cover',
  },
  placementControls: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 9,
    marginBottom: 16,
  },
  checkField: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 9,
    minWidth: 0,
    padding: 10,
    border: '1px solid var(--color-border-subtle)',
    borderRadius: 8,
    background: 'var(--color-surface-subtle)',
    color: 'var(--color-text-secondary)',
    fontSize: 12,
    lineHeight: '16px',
    '& span': {
      display: 'flex',
      flexDirection: 'column',
      gap: 3,
      minWidth: 0,
    },
    '& strong': {
      color: 'var(--color-text-primary)',
    },
    '& small': {
      color: 'var(--color-text-muted)',
      fontSize: 10,
      lineHeight: '14px',
    },
  },
  checkInput: {
    width: 16,
    height: 16,
    flexShrink: 0,
    marginTop: 1,
    accentColor: 'var(--color-primary)',
  },
  empty: {
    padding: '34px 20px',
    color: 'var(--color-text-muted)',
    fontSize: 13,
    lineHeight: '19px',
    textAlign: 'center',
  },
  muted: {
    color: 'var(--color-text-muted)',
    fontSize: 12,
  },
  link: {
    color: 'var(--color-info)',
    textDecoration: 'underline',
  },
  '@media (max-width: 1180px)': {
    createLayout: {
      gridTemplateColumns: '310px minmax(0, 1fr)',
    },
    poolsLayout: {
      gridTemplateColumns: '1fr',
    },
    stickyPanel: {
      position: 'static',
    },
  },
  '@media (max-width: 860px)': {
    page: {
      padding: '20px 16px 40px',
    },
    header: {
      flexDirection: 'column',
    },
    createLayout: {
      gridTemplateColumns: '1fr',
    },
    formGrid: {
      gridTemplateColumns: '1fr',
    },
    fullWidth: {
      gridColumn: 'auto',
    },
    sectionHeading: {
      gridColumn: 'auto',
    },
    poolRow: {
      gridTemplateColumns: '1fr auto',
    },
    placementCardHeader: {
      flexDirection: 'column',
    },
    bannerPreview: {
      width: '100%',
      height: 120,
    },
    placementControls: {
      gridTemplateColumns: '1fr',
    },
  },
});
