import { createUseStyles } from 'react-jss';

export const useLaunchpadWizardStyles = createUseStyles({
  wizard: {
    display: 'grid',
    gridTemplateColumns: '220px minmax(0, 1fr)',
    gap: 18,
    alignItems: 'start',
  },
  navigation: {
    position: 'sticky',
    top: 20,
    display: 'flex',
    flexDirection: 'column',
    gap: 7,
    padding: 12,
    border: '1px solid var(--color-border)',
    borderRadius: 12,
    background: 'var(--color-white)',
    boxShadow: 'var(--shadow-soft)',
  },
  navigationButton: {
    display: 'grid',
    gridTemplateColumns: '26px 1fr',
    gap: 9,
    alignItems: 'center',
    width: '100%',
    padding: '9px 8px',
    border: 0,
    borderRadius: 8,
    background: 'transparent',
    color: 'var(--color-text-muted)',
    fontSize: 12,
    fontWeight: 600,
    textAlign: 'left',
  },
  activeNavigationButton: {
    background: 'var(--color-primary-soft)',
    color: 'var(--color-primary-dark)',
  },
  stepNumber: {
    display: 'grid',
    placeItems: 'center',
    width: 26,
    height: 26,
    borderRadius: '50%',
    background: 'var(--color-surface-muted)',
    fontWeight: 700,
  },
  content: {
    minWidth: 0,
    border: '1px solid var(--color-border)',
    borderRadius: 12,
    background: 'var(--color-white)',
    boxShadow: 'var(--shadow-soft)',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    padding: '16px 18px',
    borderBottom: '1px solid var(--color-border-subtle)',
  },
  title: {
    fontSize: 18,
    lineHeight: '23px',
    fontWeight: 700,
  },
  hint: {
    marginTop: 4,
    color: 'var(--color-text-muted)',
    fontSize: 12,
    lineHeight: '17px',
  },
  body: {
    padding: 18,
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '15px 14px',
  },
  fullWidth: {
    gridColumn: '1 / -1',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    minWidth: 0,
  },
  label: {
    color: 'var(--color-text-secondary)',
    fontSize: 12,
    fontWeight: 700,
  },
  helper: {
    color: 'var(--color-text-muted)',
    fontSize: 11,
    lineHeight: '15px',
  },
  input: {
    width: '100%',
    height: 42,
    padding: '0 12px',
    border: '1px solid var(--color-border)',
    borderRadius: 8,
    background: 'var(--color-white)',
    fontSize: 14,
    '&:focus': {
      borderColor: 'var(--color-primary)',
      boxShadow: '0 0 0 3px var(--color-primary-soft)',
    },
    '&:disabled': {
      background: 'var(--color-surface-muted)',
      color: 'var(--color-text-muted)',
    },
  },
  textarea: {
    minHeight: 104,
    height: 'auto',
    padding: 12,
    resize: 'vertical',
  },
  section: {
    marginTop: 18,
    paddingTop: 18,
    borderTop: '1px solid var(--color-border-subtle)',
  },
  sectionTitle: {
    marginBottom: 10,
    fontSize: 14,
    fontWeight: 700,
  },
  canonicalCard: {
    display: 'grid',
    gridTemplateColumns: '72px 1fr',
    gap: 14,
    marginTop: 14,
    padding: 14,
    border: '1px solid var(--color-border-subtle)',
    borderRadius: 10,
    background: 'var(--color-surface-subtle)',
  },
  canonicalLogo: {
    width: 72,
    height: 72,
    borderRadius: 12,
    objectFit: 'cover',
    background: 'var(--color-surface-muted)',
  },
  source: {
    display: 'inline-flex',
    width: 'fit-content',
    marginLeft: 6,
    padding: '2px 6px',
    borderRadius: 999,
    background: 'var(--color-primary-soft)',
    color: 'var(--color-primary-dark)',
    fontSize: 10,
    fontWeight: 700,
  },
  assetGrid: {
    display: 'grid',
    gridTemplateColumns: '180px minmax(0, 1fr)',
    gap: 14,
    alignItems: 'start',
    padding: 14,
    border: '1px solid var(--color-border-subtle)',
    borderRadius: 10,
    background: 'var(--color-surface-subtle)',
  },
  assetPreview: {
    display: 'grid',
    placeItems: 'center',
    width: '100%',
    height: 112,
    border: '1px dashed var(--color-border)',
    borderRadius: 9,
    background: 'var(--color-white)',
    color: 'var(--color-text-muted)',
    fontSize: 11,
    overflow: 'hidden',
  },
  assetImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  assetActions: {
    display: 'flex',
    gap: 8,
    marginTop: 9,
    flexWrap: 'wrap',
  },
  hiddenFile: {
    display: 'none',
  },
  button: {
    minHeight: 38,
    padding: '0 14px',
    border: '1px solid var(--color-border)',
    borderRadius: 8,
    background: 'var(--color-white)',
    color: 'var(--color-text-secondary)',
    fontSize: 12,
    fontWeight: 700,
    '&:disabled': {
      cursor: 'not-allowed',
      opacity: 0.5,
    },
  },
  primaryButton: {
    borderColor: 'var(--color-primary)',
    background: 'var(--color-primary)',
    color: 'var(--color-white)',
  },
  dangerButton: {
    borderColor: 'rgba(255, 88, 88, 0.35)',
    color: 'var(--color-danger-dark)',
  },
  repeatCard: {
    marginTop: 10,
    padding: 12,
    border: '1px solid var(--color-border-subtle)',
    borderRadius: 9,
    background: 'var(--color-surface-subtle)',
  },
  repeatHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 9,
  },
  galleryActions: {
    display: 'flex',
    gap: 6,
  },
  footer: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    padding: '14px 18px',
    borderTop: '1px solid var(--color-border-subtle)',
  },
  previewGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 10,
  },
  previewItem: {
    padding: 11,
    borderRadius: 9,
    background: 'var(--color-surface-subtle)',
    fontSize: 12,
    lineHeight: '18px',
    overflowWrap: 'anywhere',
  },
  previewLabel: {
    marginBottom: 4,
    color: 'var(--color-text-muted)',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  readiness: {
    marginTop: 14,
    padding: 12,
    border: '1px solid rgba(255, 199, 2, 0.45)',
    borderRadius: 9,
    background: 'var(--color-warning-soft)',
    color: 'var(--color-text-secondary)',
    fontSize: 12,
    lineHeight: '18px',
  },
  ready: {
    borderColor: 'rgba(4, 165, 132, 0.35)',
    background: 'var(--color-primary-soft)',
  },
  issueList: {
    margin: '7px 0 0 18px',
  },
  '@media (max-width: 1080px)': {
    wizard: {
      gridTemplateColumns: '1fr',
    },
    navigation: {
      position: 'static',
      display: 'grid',
      gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    },
  },
  '@media (max-width: 760px)': {
    navigation: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    formGrid: {
      gridTemplateColumns: '1fr',
    },
    fullWidth: {
      gridColumn: 'auto',
    },
    assetGrid: {
      gridTemplateColumns: '1fr',
    },
    previewGrid: {
      gridTemplateColumns: '1fr',
    },
  },
});
