import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  page: {
    padding: "24px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    gap: "16px",
    flexWrap: "wrap",
  },
  titleBlock: {
    "& h1": {
      margin: [0, 0, 6, 0],
      fontSize: "28px",
      lineHeight: "34px",
    },
    "& p": {
      margin: 0,
      color: "var(--color-text-muted)",
      fontSize: "14px",
    },
  },
  headerActions: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    flexWrap: "wrap",
    "& input": {
      minWidth: "260px",
      border: "1px solid var(--color-border)",
      borderRadius: "8px",
      padding: "10px 12px",
      fontSize: "14px",
    },
    "& button": {
      border: "none",
      borderRadius: "8px",
      padding: "10px 16px",
      background: "var(--color-primary)",
      color: "var(--color-white)",
      fontWeight: "var(--font-weight-semibold)",
      cursor: "pointer",
    },
  },
  card: {
    background: "var(--color-white)",
    borderRadius: "12px",
    border: "1px solid #E6EBF1",
    overflow: "hidden",
  },
  tableHead: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 0.8fr 0.8fr 0.8fr 1.6fr",
    gap: "12px",
    padding: "14px 16px",
    background: "#F8F8F9",
    color: "var(--color-text-muted)",
    fontSize: "12px",
    fontWeight: "var(--font-weight-semibold)",
  },
  tableRow: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 0.8fr 0.8fr 0.8fr 1.6fr",
    gap: "12px",
    padding: "16px",
    alignItems: "center",
    borderTop: "1px solid #EEF2F6",
    "& img": {
      width: "40px",
      height: "40px",
      borderRadius: "10px",
      objectFit: "cover",
      flexShrink: 0,
    },
  },
  tabMeta: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    minWidth: 0,
    "& strong": {
      display: "block",
      marginBottom: "4px",
    },
    "& p": {
      margin: 0,
      color: "var(--color-text-muted)",
      fontSize: "12px",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
      maxWidth: "320px",
    },
  },
  emptyState: {
    padding: "32px 20px",
    textAlign: "center",
    color: "var(--color-text-muted)",
  },
  tag: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "999px",
    padding: "6px 10px",
    fontSize: "12px",
    fontWeight: "var(--font-weight-semibold)",
    width: "fit-content",
  },
  activeTag: {
    background: "rgba(4, 165, 132, 0.12)",
    color: "var(--color-primary)",
  },
  inactiveTag: {
    background: "rgba(115, 128, 148, 0.12)",
    color: "var(--color-text-muted)",
  },
  globalTag: {
    background: "rgba(15, 98, 254, 0.10)",
    color: "#0F62FE",
  },
  rowActions: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    "& button": {
      border: "1px solid var(--color-border)",
      background: "var(--color-white)",
      borderRadius: "8px",
      padding: "8px 12px",
      fontSize: "12px",
      cursor: "pointer",
    },
  },
  dangerButton: {
    color: "#D14141",
  },
  modalBody: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px 16px",
    "& label": {
      display: "flex",
      flexDirection: "column",
      gap: "6px",
      fontSize: "13px",
      fontWeight: "var(--font-weight-semibold)",
      color: "var(--color-text-strong)",
    },
    "& input, & textarea, & select": {
      width: "100%",
      boxSizing: "border-box",
      border: "1px solid var(--color-border)",
      borderRadius: "8px",
      padding: "9px 11px",
      fontSize: "14px",
      fontFamily: "inherit",
      background: "var(--color-white)",
      "&:focus": {
        outline: "none",
        borderColor: "var(--color-primary)",
        boxShadow: "0 0 0 3px rgba(4, 165, 132, 0.12)",
      },
    },
    "& select": {
      appearance: "none",
      backgroundImage:
        "url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8' fill='none'><path d='M1 1.5L6 6.5L11 1.5' stroke='%23738094' stroke-width='1.6' stroke-linecap='round' stroke-linejoin='round'/></svg>\")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "right 12px center",
      paddingRight: "30px",
      cursor: "pointer",
    },
    "& textarea": {
      minHeight: "60px",
      resize: "vertical",
    },
  },
  codeArea: {
    fontFamily: "'Source Code Pro', ui-monospace, monospace !important",
    fontSize: "13px !important",
    minHeight: "56px !important",
  },
  fullWidth: {
    gridColumn: "1 / -1",
  },
  switches: {
    display: "flex",
    gap: "20px",
    flexWrap: "wrap",
    padding: "12px 14px",
    background: "#F8FAFB",
    border: "1px solid #E6EBF1",
    borderRadius: "10px",
  },
  switchLabel: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: "13px",
    cursor: "pointer",
    "& input": {
      width: "16px",
      height: "16px",
      margin: 0,
      accentColor: "var(--color-primary)",
    },
  },
  columnsBlock: {
    border: "1px solid #E6EBF1",
    borderRadius: "10px",
    padding: "12px 14px",
  },
  columnsEmpty: {
    color: "var(--color-text-muted)",
    fontSize: "13px",
    padding: "8px 2px 2px",
  },
  columnsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "12px",
    gap: "12px",
    "& h3": {
      margin: 0,
      fontSize: "15px",
      fontWeight: "var(--font-weight-bold)",
    },
    "& button": {
      border: "none",
      borderRadius: "8px",
      padding: "8px 12px",
      background: "var(--color-primary)",
      color: "var(--color-white)",
      fontSize: "13px",
      fontWeight: "var(--font-weight-semibold)",
      cursor: "pointer",
    },
  },
  columnRow: {
    display: "grid",
    gridTemplateColumns: "1.5fr 1.1fr 72px auto auto",
    gap: "8px",
    alignItems: "center",
    marginBottom: "8px",
    "& input, & select": {
      width: "100%",
      boxSizing: "border-box",
      border: "1px solid var(--color-border)",
      borderRadius: "8px",
      padding: "8px 10px",
      fontSize: "13px",
      fontFamily: "inherit",
      background: "var(--color-white)",
    },
    "& select": {
      appearance: "none",
      backgroundImage:
        "url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8' fill='none'><path d='M1 1.5L6 6.5L11 1.5' stroke='%23738094' stroke-width='1.6' stroke-linecap='round' stroke-linejoin='round'/></svg>\")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "right 10px center",
      paddingRight: "26px",
      cursor: "pointer",
    },
  },
  enabledBox: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    justifyContent: "center",
    fontSize: "12px",
    fontWeight: "var(--font-weight-semibold)",
    whiteSpace: "nowrap",
    "& input": {
      width: "16px",
      height: "16px",
      accentColor: "var(--color-primary)",
    },
  },
  columnActions: {
    display: "flex",
    gap: "6px",
    "& button": {
      border: "1px solid var(--color-border)",
      background: "var(--color-white)",
      borderRadius: "8px",
      width: "30px",
      height: "32px",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
      fontSize: "13px",
      color: "var(--color-text-strong)",
    },
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    paddingTop: "4px",
    "& button": {
      borderRadius: "8px",
      padding: "10px 18px",
      fontWeight: "var(--font-weight-semibold)",
      fontSize: "14px",
      cursor: "pointer",
    },
  },
  secondaryButton: {
    border: "1px solid var(--color-border)",
    background: "var(--color-white)",
    color: "var(--color-text-strong)",
  },
  primaryButton: {
    border: "none",
    background: "var(--color-primary)",
    color: "var(--color-white)",
    "&:disabled": {
      opacity: 0.6,
      cursor: "not-allowed",
    },
  },
});
