import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  page: {
    minHeight: "100vh",
    padding: 24,
    background: "var(--color-surface-muted)",
    color: "var(--color-text-primary)",
    boxSizing: "border-box",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 16,
    flexWrap: "wrap",
    "& h1": {
      margin: [0, 0, 4, 0],
      fontSize: 25,
      lineHeight: "32px",
      fontWeight: "var(--font-weight-semibold)",
      letterSpacing: 0,
    },
    "& p": {
      margin: 0,
      color: "var(--color-text-muted)",
      fontSize: 13,
      lineHeight: "18px",
    },
  },
  headerActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    "& input, & select": {
      minHeight: 38,
      border: "1px solid var(--color-border)",
      borderRadius: 8,
      background: "var(--color-white)",
      color: "var(--color-text-primary)",
      padding: "8px 10px",
      fontSize: 13,
      boxSizing: "border-box",
    },
    "& input": {
      minWidth: 260,
    },
  },
  button: {
    minHeight: 36,
    border: "1px solid var(--color-border)",
    borderRadius: 8,
    background: "var(--color-white)",
    color: "var(--color-text-secondary)",
    padding: "8px 12px",
    fontSize: 13,
    lineHeight: "18px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    boxShadow: "0 1px 2px rgba(16, 24, 40, 0.06)",
    whiteSpace: "nowrap",
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.55,
    },
  },
  primaryButton: {
    minHeight: 38,
    border: "1px solid #027A48",
    borderRadius: 8,
    background: "#039855",
    color: "var(--color-white)",
    padding: "8px 14px",
    fontSize: 13,
    lineHeight: "18px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    boxShadow: "0 8px 18px rgba(3, 152, 85, 0.22)",
    whiteSpace: "nowrap",
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.6,
    },
  },
  warningButton: {
    minHeight: 38,
    border: "1px solid #DC6803",
    borderRadius: 8,
    background: "#F79009",
    color: "var(--color-white)",
    padding: "8px 14px",
    fontSize: 13,
    lineHeight: "18px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    boxShadow: "0 8px 18px rgba(247, 144, 9, 0.22)",
    whiteSpace: "nowrap",
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.6,
    },
  },
  secondaryButton: {
    minHeight: 38,
    border: "1px solid #FDA29B",
    borderRadius: 8,
    background: "#FFFBFA",
    color: "var(--color-danger-dark)",
    padding: "8px 14px",
    fontSize: 13,
    lineHeight: "18px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    boxShadow: "0 1px 2px rgba(16, 24, 40, 0.06)",
    whiteSpace: "nowrap",
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.6,
    },
  },
  mutedButton: {
    minHeight: 38,
    border: "1px solid var(--color-border)",
    borderRadius: 8,
    background: "var(--color-surface-subtle)",
    color: "var(--color-text-secondary)",
    padding: "8px 14px",
    fontSize: 13,
    lineHeight: "18px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    boxShadow: "0 1px 2px rgba(16, 24, 40, 0.04)",
    whiteSpace: "nowrap",
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.6,
    },
  },
  workspace: {
    display: "grid",
    gridTemplateColumns: "360px minmax(0, 1fr)",
    gap: 16,
    alignItems: "start",
    "@media (max-width: 1180px)": {
      gridTemplateColumns: "1fr",
    },
  },
  listPane: {
    minWidth: 0,
  },
  listHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    color: "var(--color-text-secondary)",
    fontSize: 12,
    "& strong": {
      color: "var(--color-text-primary)",
      fontSize: 13,
    },
  },
  caseList: {
    display: "grid",
    gap: 10,
  },
  caseCard: {
    width: "100%",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    background: "var(--color-white)",
    padding: 12,
    textAlign: "left",
    cursor: "pointer",
    boxShadow: "0 8px 18px rgba(16, 24, 40, 0.07)",
    transition: "border-color 120ms ease, box-shadow 120ms ease",
    "&:hover": {
      borderColor: "#98A2B3",
      boxShadow: "0 12px 24px rgba(16, 24, 40, 0.11)",
    },
  },
  caseCardActive: {
    borderColor: "#039855",
    boxShadow: "0 12px 24px rgba(3, 152, 85, 0.16)",
  },
  caseCardMeta: {
    display: "flex",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 10,
    color: "var(--color-text-muted)",
    fontSize: 12,
    lineHeight: "17px",
    "& span": {
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
  },
  countGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 6,
    marginTop: 10,
    "& span": {
      border: "1px solid var(--color-border-subtle)",
      borderRadius: 8,
      background: "var(--color-surface-subtle)",
      color: "var(--color-text-muted)",
      padding: "6px 7px",
      fontSize: 11,
      lineHeight: "15px",
      fontWeight: "var(--font-weight-semibold)",
    },
    "& strong": {
      display: "block",
      color: "var(--color-text-primary)",
      fontSize: 14,
      lineHeight: "18px",
      marginTop: 2,
    },
  },
  pagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 12,
    color: "var(--color-text-muted)",
    fontSize: 12,
  },
  detailPane: {
    minWidth: 0,
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    background: "var(--color-white)",
    padding: 16,
    boxShadow: "0 12px 28px rgba(16, 24, 40, 0.08)",
  },
  emptyState: {
    minHeight: 420,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px dashed var(--color-border)",
    borderRadius: 8,
    color: "var(--color-text-muted)",
    fontSize: 14,
    fontWeight: "var(--font-weight-semibold)",
  },
  empty: {
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    background: "var(--color-white)",
    padding: 14,
    color: "var(--color-text-muted)",
    fontSize: 13,
    lineHeight: "18px",
  },
  projectIdentity: {
    display: "grid",
    gridTemplateColumns: "42px minmax(0, 1fr)",
    gap: 10,
    alignItems: "center",
    minWidth: 0,
    "& strong": {
      display: "block",
      color: "var(--color-text-primary)",
      fontSize: 14,
      lineHeight: "19px",
      fontWeight: "var(--font-weight-semibold)",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    "& small": {
      display: "block",
      marginTop: 2,
      color: "var(--color-text-muted)",
      fontSize: 12,
      lineHeight: "16px",
      fontWeight: "var(--font-weight-semibold)",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
  },
  projectIdentityLarge: {
    gridTemplateColumns: "54px minmax(0, 1fr)",
    "& strong": {
      fontSize: 20,
      lineHeight: "27px",
    },
    "& small": {
      fontSize: 13,
      lineHeight: "18px",
    },
  },
  logoBox: {
    width: 42,
    height: 42,
    border: "1px solid var(--color-border)",
    borderRadius: 8,
    background: "var(--color-surface-subtle)",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--color-text-secondary)",
    fontSize: 11,
    fontWeight: "var(--font-weight-semibold)",
    textTransform: "uppercase",
    "$projectIdentityLarge &": {
      width: 54,
      height: 54,
      fontSize: 13,
    },
    "& img": {
      width: "100%",
      height: "100%",
      display: "block",
      objectFit: "cover",
    },
  },
  projectHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
    flexWrap: "wrap",
  },
  projectHeaderActions: {
    display: "grid",
    justifyItems: "end",
    gap: 8,
    minWidth: 240,
    "@media (max-width: 760px)": {
      justifyItems: "start",
      width: "100%",
    },
  },
  projectBadges: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    justifyContent: "flex-end",
    "& span": {
      border: "1px solid var(--color-border-subtle)",
      borderRadius: 999,
      background: "var(--color-surface-subtle)",
      color: "var(--color-text-secondary)",
      padding: "5px 8px",
      fontSize: 12,
      lineHeight: "16px",
      fontWeight: "var(--font-weight-semibold)",
      whiteSpace: "nowrap",
    },
  },
  sourceActions: {
    display: "flex",
    gap: 8,
    justifyContent: "flex-end",
    flexWrap: "wrap",
    "@media (max-width: 760px)": {
      justifyContent: "flex-start",
    },
  },
  linkButton: {
    minHeight: 38,
    border: "1px solid #B2DDFF",
    borderRadius: 8,
    background: "#EFF8FF",
    color: "var(--color-info)",
    padding: "8px 12px",
    fontSize: 13,
    lineHeight: "20px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    textDecoration: "none",
    boxSizing: "border-box",
    whiteSpace: "nowrap",
  },
  editedBadge: {
    borderColor: "#A6F4C5 !important",
    background: "#ECFDF3 !important",
    color: "#027A48 !important",
  },
  confirmedBadge: {
    borderColor: "#B2DDFF !important",
    background: "#EFF8FF !important",
    color: "var(--color-info) !important",
  },
  notice: {
    border: "1px solid #B2DDFF",
    borderRadius: 8,
    background: "#EFF8FF",
    color: "var(--color-info)",
    padding: "8px 10px",
    marginBottom: 12,
    fontSize: 12,
    lineHeight: "17px",
    fontWeight: "var(--font-weight-semibold)",
  },
  metrics: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(120px, 1fr))",
    gap: 10,
    marginBottom: 14,
    "@media (max-width: 760px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
  },
  metric: {
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    background: "var(--color-surface-raised)",
    padding: "10px 12px",
    "& span": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: 11,
      lineHeight: "15px",
      fontWeight: "var(--font-weight-semibold)",
      textTransform: "uppercase",
    },
    "& strong": {
      display: "block",
      color: "var(--color-text-primary)",
      fontSize: 22,
      lineHeight: "28px",
      marginTop: 3,
    },
  },
  importResult: {
    border: "1px solid var(--color-border)",
    borderRadius: 8,
    background: "var(--color-white)",
    padding: 14,
    marginBottom: 16,
    boxShadow: "0 10px 24px rgba(16, 24, 40, 0.08)",
  },
  importResultGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(110px, 1fr))",
    gap: 8,
    "@media (max-width: 1180px)": {
      gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    },
    "@media (max-width: 640px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
    "& div": {
      border: "1px solid var(--color-border-subtle)",
      borderRadius: 8,
      background: "var(--color-surface-subtle)",
      padding: "8px 10px",
      minWidth: 0,
    },
    "& span": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: 11,
      lineHeight: "15px",
      fontWeight: "var(--font-weight-semibold)",
      textTransform: "uppercase",
    },
    "& strong": {
      display: "block",
      marginTop: 2,
      color: "var(--color-text-primary)",
      fontSize: 16,
      lineHeight: "22px",
      fontWeight: "var(--font-weight-semibold)",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
  },
  section: {
    borderTop: "1px solid var(--color-border-subtle)",
    paddingTop: 14,
    marginTop: 14,
  },
  sectionHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
    flexWrap: "wrap",
    "& h2": {
      margin: 0,
      color: "var(--color-text-primary)",
      fontSize: 15,
      lineHeight: "21px",
      fontWeight: "var(--font-weight-semibold)",
      letterSpacing: 0,
    },
  },
  summaryBand: {
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    background: "var(--color-surface-raised)",
    padding: 12,
    marginBottom: 10,
  },
  progressBar: {
    height: 14,
    width: "100%",
    borderRadius: 999,
    background: "var(--color-border-subtle)",
    overflow: "hidden",
    display: "flex",
  },
  unlockedBar: {
    display: "block",
    height: "100%",
    background: "#039855",
  },
  lockedBar: {
    display: "block",
    height: "100%",
    background: "#F79009",
  },
  untrackedBar: {
    display: "block",
    height: "100%",
    background: "var(--color-text-muted)",
  },
  summaryLegend: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
    marginTop: 8,
    color: "var(--color-text-secondary)",
    fontSize: 12,
    lineHeight: "17px",
    fontWeight: "var(--font-weight-semibold)",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 8,
    "@media (max-width: 1100px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
    },
    "& label": {
      display: "grid",
      gap: 4,
      minWidth: 0,
    },
    "& span": {
      color: "var(--color-text-muted)",
      fontSize: 11,
      lineHeight: "15px",
      fontWeight: "var(--font-weight-semibold)",
    },
    "& input": {
      width: "100%",
      minHeight: 34,
      border: "1px solid var(--color-border)",
      borderRadius: 8,
      background: "var(--color-white)",
      color: "var(--color-text-primary)",
      padding: "7px 8px",
      fontSize: 12,
      boxSizing: "border-box",
    },
  },
  tableWrap: {
    overflowX: "auto",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    background: "var(--color-white)",
  },
  editTable: {
    width: "100%",
    minWidth: 980,
    borderCollapse: "collapse",
    "& th": {
      textAlign: "left",
      color: "var(--color-text-muted)",
      background: "var(--color-surface-subtle)",
      borderBottom: "1px solid var(--color-border-subtle)",
      padding: "8px 8px",
      fontSize: 11,
      lineHeight: "15px",
      fontWeight: "var(--font-weight-semibold)",
      whiteSpace: "nowrap",
    },
    "& td": {
      borderBottom: "1px solid var(--color-border-subtle)",
      padding: 6,
      verticalAlign: "top",
    },
    "& input": {
      width: "100%",
      minHeight: 32,
      border: "1px solid var(--color-border)",
      borderRadius: 8,
      background: "var(--color-white)",
      color: "var(--color-text-primary)",
      padding: "6px 8px",
      fontSize: 12,
      lineHeight: "17px",
      boxSizing: "border-box",
    },
  },
  removeButton: {
    minHeight: 32,
    border: "1px solid #FECDCA",
    borderRadius: 8,
    background: "#FFFBFA",
    color: "var(--color-danger-dark)",
    padding: "6px 8px",
    fontSize: 12,
    lineHeight: "17px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
  },
  tableEmpty: {
    textAlign: "center",
    color: "var(--color-text-muted)",
    fontSize: 13,
    padding: "16px !important",
  },
  miniBar: {
    width: 92,
    height: 10,
    borderRadius: 999,
    background: "var(--color-border-subtle)",
    overflow: "hidden",
    display: "flex",
    marginTop: 4,
    marginBottom: 5,
  },
  applyBar: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 10,
    alignItems: "stretch",
    borderTop: "1px solid var(--color-border-subtle)",
    marginTop: 16,
    paddingTop: 14,
    "@media (max-width: 760px)": {
      gridTemplateColumns: "1fr",
    },
    "& textarea": {
      width: "100%",
      minHeight: 72,
      border: "1px solid var(--color-border)",
      borderRadius: 8,
      background: "var(--color-white)",
      color: "var(--color-text-primary)",
      padding: "9px 10px",
      fontSize: 13,
      lineHeight: "18px",
      resize: "vertical",
      boxSizing: "border-box",
    },
  },
  applyActions: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "flex-end",
    gap: 8,
    flexWrap: "wrap",
  },
  applyPrimaryActions: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "flex-end",
    gap: 8,
    flexWrap: "wrap",
  },
  caseResolutionActions: {
    display: "grid",
    gap: 6,
    justifyItems: "end",
    maxWidth: 360,
    paddingLeft: 12,
    borderLeft: "1px solid var(--color-border-subtle)",
    "& small": {
      color: "var(--color-text-muted)",
      fontSize: 12,
      lineHeight: "17px",
      textAlign: "right",
    },
    "@media (max-width: 760px)": {
      width: "100%",
      maxWidth: "none",
      justifyItems: "start",
      paddingLeft: 0,
      paddingTop: 10,
      borderLeft: "none",
      borderTop: "1px solid var(--color-border-subtle)",
      "& small": {
        textAlign: "left",
      },
    },
  },
  caseResolutionButtons: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    justifyContent: "flex-end",
    "@media (max-width: 760px)": {
      justifyContent: "flex-start",
    },
  },
  rawDetails: {
    marginTop: 12,
    "& summary": {
      color: "var(--color-info)",
      cursor: "pointer",
      fontSize: 12,
      lineHeight: "18px",
      fontWeight: "var(--font-weight-semibold)",
    },
    "& pre": {
      maxHeight: 280,
      overflow: "auto",
      border: "1px solid #1D2939",
      borderRadius: 8,
      background: "var(--color-text-primary)",
      color: "var(--color-border-subtle)",
      padding: 12,
      fontSize: 12,
      lineHeight: "18px",
      whiteSpace: "pre-wrap",
      overflowWrap: "anywhere",
    },
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 30,
    background: "rgba(16, 24, 40, 0.38)",
  },
  modal: {
    position: "fixed",
    top: "50%",
    left: "50%",
    zIndex: 31,
    width: "min(480px, calc(100vw - 32px))",
    transform: "translate(-50%, -50%)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    background: "var(--color-white)",
    boxShadow: "0 24px 48px rgba(16, 24, 40, 0.24)",
    padding: 18,
    boxSizing: "border-box",
    "& h2": {
      margin: [0, 0, 8, 0],
      color: "var(--color-text-primary)",
      fontSize: 18,
      lineHeight: "24px",
      fontWeight: "var(--font-weight-semibold)",
      letterSpacing: 0,
    },
    "& p": {
      margin: [0, 0, 14, 0],
      color: "var(--color-text-secondary)",
      fontSize: 13,
      lineHeight: "19px",
    },
  },
  bulkProgress: {
    border: "1px solid var(--color-border-subtle)",
    borderRadius: 8,
    background: "var(--color-surface-subtle)",
    padding: "10px 12px",
    marginBottom: 14,
    "& span": {
      display: "block",
      color: "var(--color-text-primary)",
      fontSize: 20,
      lineHeight: "26px",
      fontWeight: "var(--font-weight-semibold)",
    },
    "& strong": {
      display: "block",
      marginTop: 4,
      color: "var(--color-text-secondary)",
      fontSize: 12,
      lineHeight: "17px",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    "& small": {
      display: "block",
      marginTop: 4,
      color: "var(--color-danger-dark)",
      fontSize: 12,
      lineHeight: "17px",
      fontWeight: "var(--font-weight-semibold)",
    },
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    flexWrap: "wrap",
  },
});
