import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  page: {
    padding: "24px",
    color: "var(--color-text-primary)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    marginBottom: "20px",
    flexWrap: "wrap",
    "& h1": {
      margin: [0, 0, 6, 0],
      fontSize: "28px",
      lineHeight: "34px",
    },
    "& p": {
      margin: 0,
      color: "var(--color-text-muted)",
      fontSize: "14px",
      lineHeight: "20px",
      maxWidth: "720px",
    },
  },
  headerStatus: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "6px",
    color: "var(--color-text-muted)",
    fontSize: "13px",
    "& strong": {
      color: "var(--color-text-primary)",
      fontSize: "14px",
    },
  },
  panel: {
    background: "var(--color-white)",
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    padding: "18px",
    marginBottom: "18px",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "16px",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: "16px",
    "& h2": {
      margin: 0,
      fontSize: "18px",
      lineHeight: "24px",
    },
  },
  controlsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(150px, 1fr))",
    gap: "14px",
    marginBottom: "16px",
    "@media (max-width: 1000px)": {
      gridTemplateColumns: "repeat(2, minmax(150px, 1fr))",
    },
    "@media (max-width: 620px)": {
      gridTemplateColumns: "1fr",
    },
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    fontSize: "13px",
    fontWeight: "var(--font-weight-semibold)",
    color: "#445066",
    "& input": {
      border: "1px solid var(--color-border)",
      borderRadius: "8px",
      padding: "10px 12px",
      fontSize: "14px",
      color: "var(--color-text-primary)",
      minWidth: 0,
    },
    "& span": {
      color: "var(--color-text-muted)",
      fontSize: "12px",
      lineHeight: "16px",
      fontWeight: "var(--font-weight-medium)",
    },
  },
  switches: {
    display: "flex",
    gap: "14px",
    flexWrap: "wrap",
    marginBottom: "16px",
  },
  checkRow: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    color: "#445066",
    fontSize: "14px",
    lineHeight: "18px",
    "& input": {
      width: "16px",
      height: "16px",
      accentColor: "var(--color-primary)",
    },
  },
  actions: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  primaryButton: {
    border: "none",
    borderRadius: "8px",
    padding: "10px 16px",
    background: "var(--color-primary)",
    color: "var(--color-white)",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    minHeight: "40px",
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.58,
    },
  },
  secondaryButton: {
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    padding: "10px 16px",
    background: "var(--color-white)",
    color: "var(--color-text-primary)",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    minHeight: "40px",
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.58,
    },
  },
  dangerButton: {
    border: "none",
    borderRadius: "8px",
    padding: "10px 16px",
    background: "#EF5B5B",
    color: "var(--color-white)",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    minHeight: "40px",
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.48,
    },
  },
  warning: {
    borderRadius: "8px",
    padding: "10px 12px",
    background: "rgba(245, 165, 36, 0.12)",
    color: "#A66600",
    fontSize: "13px",
    lineHeight: "18px",
    marginTop: "12px",
  },
  progressPanel: {
    marginTop: "16px",
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    padding: "14px",
    background: "#FCFDFE",
  },
  progressHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "center",
    marginBottom: "10px",
    "& strong": {
      fontSize: "14px",
      color: "var(--color-text-primary)",
    },
    "& span": {
      fontSize: "16px",
      fontWeight: "var(--font-weight-semibold)",
      color: "var(--color-primary)",
    },
  },
  progressTrack: {
    height: "10px",
    borderRadius: "999px",
    background: "#E8EEF4",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    minWidth: "0",
    borderRadius: "999px",
    background: "var(--color-primary)",
    transition: "width 420ms ease",
    position: "relative",
    overflow: "hidden",
    "&:after": {
      content: '""',
      position: "absolute",
      top: 0,
      bottom: 0,
      width: "80px",
      background: "rgba(255,255,255,0.28)",
      transform: "skewX(-20deg)",
      animation: "$progressShine 1.4s linear infinite",
    },
  },
  progressFillSettled: {
    "&:after": {
      display: "none",
      animation: "none",
    },
  },
  progressMessage: {
    margin: [10, 0, 0, 0],
    color: "var(--color-text-muted)",
    fontSize: "13px",
    lineHeight: "18px",
  },
  progressMeta: {
    marginTop: "10px",
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    color: "var(--color-text-muted)",
    fontSize: "12px",
    "& span": {
      borderRadius: "999px",
      background: "rgba(115, 128, 148, 0.1)",
      padding: "5px 8px",
    },
  },
  "@keyframes progressShine": {
    "0%": {
      left: "-90px",
    },
    "100%": {
      left: "110%",
    },
  },
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "12px",
    "@media (max-width: 620px)": {
      gridTemplateColumns: "1fr",
    },
  },
  metric: {
    border: "1px solid #EEF2F6",
    borderRadius: "8px",
    padding: "14px",
    minHeight: "82px",
    background: "#FCFDFE",
    "& span": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: "12px",
      lineHeight: "16px",
      marginBottom: "8px",
    },
    "& strong": {
      display: "block",
      fontSize: "24px",
      lineHeight: "28px",
      color: "var(--color-text-primary)",
    },
  },
  metricGood: {
    borderColor: "rgba(4, 165, 132, 0.28)",
    background: "rgba(4, 165, 132, 0.07)",
  },
  metricWarn: {
    borderColor: "rgba(245, 165, 36, 0.34)",
    background: "rgba(245, 165, 36, 0.08)",
  },
  metricBad: {
    borderColor: "rgba(239, 91, 91, 0.28)",
    background: "rgba(239, 91, 91, 0.07)",
  },
  splitGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "18px",
    "@media (max-width: 980px)": {
      gridTemplateColumns: "1fr",
    },
  },
  list: {
    display: "grid",
    gap: "8px",
  },
  listRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    borderBottom: "1px solid #EEF2F6",
    paddingBottom: "8px",
    color: "#445066",
    fontSize: "14px",
    "& strong": {
      color: "var(--color-text-primary)",
    },
  },
  table: {
    overflowX: "auto",
    border: "1px solid #EEF2F6",
    borderRadius: "8px",
  },
  tableHead: {
    display: "grid",
    gridTemplateColumns: "1fr 1.2fr 1fr 1fr 1.2fr",
    minWidth: "760px",
    background: "#F8F8F9",
    color: "var(--color-text-muted)",
    fontSize: "12px",
    fontWeight: "var(--font-weight-semibold)",
    "& div": {
      padding: "12px",
    },
  },
  tableRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1.2fr 1fr 1fr 1.2fr",
    minWidth: "760px",
    borderTop: "1px solid #EEF2F6",
    fontSize: "13px",
    color: "#445066",
    "& div": {
      padding: "12px",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    "& strong": {
      color: "var(--color-text-primary)",
    },
  },
  statusTag: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "999px",
    padding: "5px 9px",
    background: "rgba(115, 128, 148, 0.12)",
    color: "#445066",
    fontSize: "12px",
    fontWeight: "var(--font-weight-semibold)",
    width: "fit-content",
  },
  statusApplied: {
    background: "rgba(4, 165, 132, 0.12)",
    color: "#03866B",
  },
  statusConflict: {
    background: "rgba(239, 91, 91, 0.12)",
    color: "#C43D3D",
  },
  historyList: {
    display: "grid",
    gap: "10px",
  },
  historyRow: {
    display: "grid",
    gridTemplateColumns: "1.3fr 0.8fr 1.4fr 1.4fr auto",
    gap: "12px",
    alignItems: "center",
    border: "1px solid #EEF2F6",
    borderRadius: "8px",
    padding: "12px",
    background: "#FCFDFE",
    "& > div": {
      minWidth: 0,
      display: "grid",
      gap: "5px",
    },
    "& strong": {
      color: "var(--color-text-primary)",
      fontSize: "13px",
      lineHeight: "17px",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    "& span": {
      color: "var(--color-text-muted)",
      fontSize: "12px",
      lineHeight: "16px",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    "@media (max-width: 980px)": {
      gridTemplateColumns: "1fr",
      alignItems: "stretch",
      "& button": {
        width: "fit-content",
      },
    },
  },
  batchSearch: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    "& input": {
      flex: "1 1 280px",
      border: "1px solid var(--color-border)",
      borderRadius: "8px",
      padding: "10px 12px",
      fontSize: "14px",
      minWidth: 0,
    },
  },
  jsonBlock: {
    margin: 0,
    padding: "14px",
    borderRadius: "8px",
    background: "var(--color-text-primary)",
    color: "#DDE7F3",
    overflow: "auto",
    maxHeight: "420px",
    fontSize: "12px",
    lineHeight: "18px",
  },
  details: {
    "& summary": {
      cursor: "pointer",
      color: "var(--color-primary)",
      fontWeight: "var(--font-weight-semibold)",
      marginBottom: "10px",
    },
  },
  emptyState: {
    padding: "22px",
    color: "var(--color-text-muted)",
    textAlign: "center",
    border: "1px dashed var(--color-border)",
    borderRadius: "8px",
  },
});
