/* eslint-disable */
import React, { useContext } from "react";
import { useRouter } from "next/router";
import { useQuery } from "react-query";
import moment from "moment";
import Link from "next/link";
import BreadCrumbs from "../../../../global/BreadCrumbs";
import image from "../../../../../public/static/main/where_next.png";
import NewsItem from "../../../../global/NewsItem";
import imageLoader from "../../../../../helpers/imageLoader";
import useFetch from "../../../../../hooks/useFetch";
import { INews, IUser } from "../../../../../types/global_types";
import { PageWrapper } from "../../CryptoMarket/styles";
import LogoAdmin from "../../../../../assets/images/favicon-32x32.svg";
import addReaction from "../../../../../http/news/addReaction";
import {
  AiBadge,
  AiViewBox,
  Categories,
  ContentText,
  ContentWrapper,
  Date,
  Details,
  ImageStyles,
  LikesButtons,
  LikesWrapper,
  NewsImage,
  Recommended,
  RecommendedItemsWrapper,
  RecommendedTitle,
  SectionHeading,
  SourcesList,
  SummaryText,
  TakeawaysList,
  Title,
  WhyMattersBox,
} from "./styles";
import { UserData } from "../Market/styles";
import Image from "next/image";
import { Category, UserInfoWrapper } from "../../../../global/NewsItem/styles";
import CommentBlock from "../../../../global/CommentBlock";
import DiscussionSummary from "../../../../global/DiscussionSummary";
import useComments from "../../../../../hooks/useComments";
import MainLike from "../../../../global/Icons/MainLike";
import MainDislike from "../../../../global/Icons/MainDislike";
import SocialLinks from "../../../../global/common/SocialLinks";
import fetchNewsItem from "../../../../../http/news/fetchNewsItem";
import { AuthContext } from "../../../../global/Layout";
import { sanitizedHtml } from "../../../../../helpers/sanitizeHtml";

const NewsItemPage = () => {
  const router = useRouter();
  const { userData } = useContext(AuthContext);
  const newsId =
    typeof router.query.id === "string" ? router.query.id : "";
  // NEWS-1 Phase 6A P2: News is a supported entity of the existing Comments/Buzz
  // engine. We scope the discussion by a per-news page key (no NewsCommentsService).
  const newsEntityKey = newsId ? `crypto-news-${newsId}` : "crypto";
  const { comments, confirmAddComment, refetch: refetchComments } = useComments(
    `comments/${newsEntityKey}`,
    `comments/${newsEntityKey}`
  );
  const { data, refetch } = useQuery(["news-item", router.query.id], () =>
    fetchNewsItem(`news/item/${router.query.id}`)
  );
  const user: IUser | null = data?.newsItem?.creator?.length
    ? data.newsItem.creator[0]
    : null;

  const confirmAddReaction = async (
    actionType: "like" | "dislike"
  ): Promise<void> => {
    await addReaction(actionType, data?.newsItem?._id || "");

    await refetch();
  };

  return (
    <>
      <PageWrapper className="news-page-wrapper">
        <ContentWrapper>
          <Title variant="h1">{data?.newsItem?.title}</Title>
          <UserData>
            {data?.newsItem?.isAdminCreate ? (
              <Image src={LogoAdmin} alt="News creator" />
            ) : (
              <img
                src={
                  user?.avatar
                    ? imageLoader(user?.avatar)
                    : user?.twitterData?.avatar
                }
                alt="News creator"
              />
            )}
            <Categories>
              <Category>{data?.newsItem?.type}</Category>
            </Categories>
            <UserInfoWrapper>
              <div>
                {data?.newsItem?.isAdminCreate
                  ? "FOMO"
                  : user?.username || user?.twitterData?.username}
              </div>
              <span>
                {moment(data?.newsItem?.date).format("MMMM Do YYYY, h:mm:ss a")}
              </span>
            </UserInfoWrapper>
          </UserData>
          <NewsImage
            src={
              data?.newsItem?.image
                ? imageLoader(data?.newsItem.image)
                : image.src
            }
            alt={data?.newsItem?.title}
          />
          {data?.newsItem?.aiGenerated ? (
            <div data-testid="ai-news-sections">
              <AiBadge trust={data?.newsItem?.trustColor} data-testid="ai-generated-badge">
                Generated by FOMO AI
              </AiBadge>

              {data?.newsItem?.summary ? (
                <>
                  <SectionHeading>Summary</SectionHeading>
                  <SummaryText data-testid="ai-summary">
                    {data.newsItem.summary}
                  </SummaryText>
                </>
              ) : null}

              {data?.newsItem?.keyPoints &&
              data.newsItem.keyPoints.length > 0 ? (
                <>
                  <SectionHeading>Key Takeaways</SectionHeading>
                  <TakeawaysList data-testid="ai-key-takeaways">
                    {data.newsItem.keyPoints.map((point: string, i: number) => (
                      <li key={i}>{point}</li>
                    ))}
                  </TakeawaysList>
                </>
              ) : null}

              <SectionHeading>Full Story</SectionHeading>
              <ContentText
                data-testid="ai-full-story"
                dangerouslySetInnerHTML={sanitizedHtml(
                  data?.newsItem?.text || ""
                )}
              ></ContentText>

              {data?.newsItem?.aiView ? (
                <>
                  <SectionHeading>FOMO AI View</SectionHeading>
                  <AiViewBox data-testid="ai-view">
                    {data.newsItem.aiView}
                  </AiViewBox>
                </>
              ) : null}

              {data?.newsItem?.whyMatters ? (
                <>
                  <SectionHeading>Why It Matters</SectionHeading>
                  <WhyMattersBox data-testid="ai-why-matters">
                    {data.newsItem.whyMatters}
                  </WhyMattersBox>
                </>
              ) : null}

              {data?.newsItem?.provenanceUrls &&
              data.newsItem.provenanceUrls.length > 0 ? (
                <>
                  <SectionHeading>Sources</SectionHeading>
                  <SourcesList data-testid="ai-sources">
                    {data.newsItem.provenanceUrls.map(
                      (url: string, i: number) => (
                        <a
                          key={i}
                          href={url}
                          target="_blank"
                          rel="noreferrer noopener"
                        >
                          <span>[{i + 1}]</span>
                          {url}
                        </a>
                      )
                    )}
                  </SourcesList>
                </>
              ) : null}
            </div>
          ) : (
            <ContentText
              dangerouslySetInnerHTML={sanitizedHtml(data?.newsItem?.text || "")}
            ></ContentText>
          )}
          <LikesWrapper>
            <p>Enjoyed the article? Show your support by giving it a like!</p>
            <LikesButtons>
              <MainLike
                likesCount={data?.newsItem?.likes?.length || 0}
                isActive={data?.newsItem?.likes?.includes(userData?._id)}
                onClick={() => confirmAddReaction("like")}
              />
              <MainDislike
                likesCount={data?.newsItem?.dislikes?.length || 0}
                isActive={data?.newsItem?.dislikes?.includes(userData?._id)}
                onClick={() => confirmAddReaction("dislike")}
              />
            </LikesButtons>
          </LikesWrapper>
          <Details>
            <span>Share</span>
            <SocialLinks
              className="blog-social"
              links={[
                {
                  href: "/",
                  key: "fs",
                },
                {
                  href: "/",
                  key: "inst",
                },
                {
                  href: "/",
                  key: "x",
                },
                {
                  href: "/",
                  key: "tg",
                },
              ]}
            />
          </Details>
        </ContentWrapper>
        {data?.newsItem?.recommendationNewsItems?.length ? (
          <Recommended>
            <RecommendedTitle variant="p">You Might Also Like</RecommendedTitle>
            <RecommendedItemsWrapper>
              {data.newsItem.recommendationNewsItems.map(
                (item: INews, i: number) => {
                  return (
                    <Link href={`/crypto/news/${item._id}`} key={i}>
                      <NewsItem newsItem={item} />
                    </Link>
                  );
                }
              )}
            </RecommendedItemsWrapper>
          </Recommended>
        ) : null}
      </PageWrapper>
      <PageWrapper>
        <DiscussionSummary page={newsEntityKey} />
        <CommentBlock
          items={comments}
          addComment={confirmAddComment}
          refetch={refetchComments}
        />
      </PageWrapper>
    </>
  );
};

export default NewsItemPage;
