import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  wrapper: {
    background: "#F8F8F9",
    borderRadius: 12,
    overflowX: "auto",
    overflowY: "hidden",
    border: "1px solid #ECEEF3",
  },
  headerRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1.2fr 1.2fr 1.2fr 1fr 1.6fr 1.6fr 1.6fr 1.4fr",
    gap: 12,
    padding: "12px 16px",
    background: "linear-gradient(180deg, var(--color-white) 0%, #F5F7FB 100%)",
    borderBottom: "1px solid #ECEEF3",

    "& > div": {
      color: "var(--color-text-muted)",
      fontWeight: "var(--font-weight-semibold)",
      fontSize: 12,
      lineHeight: "14px",
      textTransform: "uppercase",
      letterSpacing: 0.2,
    },
  },
  bodyRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1.2fr 1.2fr 1.2fr 1fr 1.6fr 1.6fr 1.6fr 1.4fr",
    gap: 12,
    padding: "14px 16px",
    borderBottom: "1px solid #ECEEF3",
    alignItems: "center",
    background: "var(--color-white)",

    "&:nth-child(even)": {
      background: "#FCFDFE",
    },
  },
  cell: {
    fontSize: 13,
    color: "var(--color-text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dealLink: {
    color: "#1B74E4",
    fontWeight: "var(--font-weight-semibold)",
    textDecoration: "none",
    cursor: "pointer",
    background: "transparent",
    border: "none",
    padding: 0,
  },
  muted: {
    color: "var(--color-text-muted)",
  },
  dealType: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 48,
    padding: "2px 8px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: "var(--font-weight-semibold)",
    textTransform: "uppercase",
    marginRight: 6,
  },
  dealTypeBuy: {
    background: "#EAF8F0",
    color: "#1D8F4E",
  },
  dealTypeSell: {
    background: "#FFEDEE",
    color: "#CF2E3D",
  },
  tickerCaps: {
    fontWeight: "var(--font-weight-semibold)",
    textTransform: "uppercase",
  },
  status: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 100,
    padding: "4px 10px",
    fontSize: 12,
    fontWeight: "var(--font-weight-semibold)",
    textTransform: "capitalize",
  },
  statusOpen: {
    background: "#FFF4DB",
    color: "#A66B00",
  },
  statusReview: {
    background: "#EAF2FF",
    color: "#315DBE",
  },
  statusResolved: {
    background: "#E8F8EE",
    color: "#177A43",
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    flexWrap: "nowrap",
    justifySelf: "end",
    width: "100%",
  },
  actionBtn: {
    border: "none",
    borderRadius: 10,
    padding: "7px 12px",
    fontSize: 12,
    fontWeight: "var(--font-weight-semibold)",
    letterSpacing: 0.2,
    cursor: "pointer",
    transition: "all .2s ease",
    outline: "none",
  },
  actionPrimary: {
    background: "linear-gradient(135deg, #1B74E4 0%, #2457CC 100%)",
    color: "var(--color-white)",
    boxShadow: "0 10px 20px rgba(27,116,228,0.24)",

    "&:hover": {
      filter: "brightness(1.04)",
      transform: "translateY(-1px)",
    },
  },
  actionSecondary: {
    background: "linear-gradient(135deg, #F5F8FF 0%, #EAF0FF 100%)",
    color: "#1E3A8A",
    border: "1px solid #D8E3FF",

    "&:hover": {
      background: "linear-gradient(135deg, #EBF2FF 0%, #DFE9FF 100%)",
    },

    "&:disabled": {
      cursor: "not-allowed",
      color: "#8A94A8",
      background: "#F4F6FA",
      borderColor: "#E5EAF3",
    },
  },
  empty: {
    padding: "24px 16px",
    textAlign: "center",
    color: "var(--color-text-muted)",
    fontWeight: "var(--font-weight-medium)",
  },
  modalContent: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  label: {
    fontSize: 13,
    color: "var(--color-text-primary)",
    fontWeight: "var(--font-weight-semibold)",
  },
  textarea: {
    width: "100%",
    minHeight: 110,
    border: "1px solid var(--color-border)",
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    color: "var(--color-text-primary)",
    resize: "vertical",
    boxSizing: "border-box",
    outline: "none",
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--color-text-primary)",
    cursor: "pointer",
    userSelect: "none",

    "& $checkboxInput:checked + $checkboxCustom": {
      background: "#1B74E4",
      borderColor: "#1B74E4",
    },

    "& $checkboxInput:checked + $checkboxCustom::after": {
      opacity: 1,
      transform: "rotate(45deg) scale(1)",
    },
  },
  checkboxInput: {
    position: "absolute",
    opacity: 0,
    width: 1,
    height: 1,
    pointerEvents: "none",
  },
  checkboxCustom: {
    position: "relative",
    width: 18,
    height: 18,
    borderRadius: 5,
    border: "1px solid #C8D3E7",
    background: "var(--color-white)",
    flexShrink: 0,
    transition: "all .2s ease",

    "&::after": {
      content: "\"\"",
      position: "absolute",
      left: 5,
      top: 1,
      width: 5,
      height: 10,
      borderRight: "2px solid var(--color-white)",
      borderBottom: "2px solid var(--color-white)",
      transform: "rotate(45deg) scale(0.7)",
      transformOrigin: "center center",
      opacity: 0,
      transition: "all .2s ease",
    },
  },
  modalActions: {
    display: "flex",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 8,
    width: "100%",
  },
  modalActionBtn: {
    flex: 1,
    width: "50%",
    minHeight: 46,
    borderRadius: 10,
    fontSize: 14,
    fontWeight: "var(--font-weight-semibold)",
    lineHeight: "18px",
  },
  modalCancelBtn: {
    background: "#F5F8FF !important",
    border: "1px solid #D8E3FF !important",
    color: "#1E3A8A !important",
    boxShadow: "none !important",

    "&:hover": {
      background: "#EBF2FF !important",
    },
  },
  modalConfirmBtn: {
    background: "linear-gradient(135deg, #1B74E4 0%, #2457CC 100%) !important",
    color: "var(--color-white) !important",
    border: "none !important",

    "&:hover": {
      filter: "brightness(1.04)",
    },
  },
  recipientPreview: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginTop: 8,
  },
  recipientRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 10,
    border: "1px solid #E6EBF5",
    background: "#FAFCFF",
  },
  recipientRowSelected: {
    border: "1px solid #CFE0FF",
    background: "#F1F6FF",
  },
  recipientAvatar: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    objectFit: "cover",
    background: "#EDF1F7",
    flexShrink: 0,
  },
  recipientMeta: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    flex: 1,
  },
  recipientName: {
    color: "var(--color-text-primary)",
    fontSize: 13,
    fontWeight: "var(--font-weight-semibold)",
    lineHeight: "16px",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",

    "& span": {
      color: "var(--color-text-muted)",
      fontWeight: "var(--font-weight-medium)",
    },
  },
  recipientWallet: {
    color: "var(--color-text-muted)",
    fontSize: 12,
    lineHeight: "14px",
  },
  recipientBadge: {
    fontSize: 11,
    fontWeight: "var(--font-weight-semibold)",
    color: "#1E3A8A",
    background: "#E7EEFF",
    borderRadius: 999,
    padding: "4px 8px",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  detailsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 12,
  },
  detailsCard: {
    border: "1px solid #E6EBF5",
    borderRadius: 10,
    background: "#FAFCFF",
    padding: 12,
  },
  detailsTitle: {
    margin: 0,
    color: "var(--color-text-muted)",
    fontSize: 12,
    fontWeight: "var(--font-weight-semibold)",
    textTransform: "uppercase",
  },
  detailsValue: {
    marginTop: 8,
    color: "var(--color-text-primary)",
    fontSize: 14,
    fontWeight: "var(--font-weight-semibold)",
    wordBreak: "break-word",
  },
  detailSectionTitle: {
    margin: "4px 0 8px",
    color: "var(--color-text-primary)",
    fontSize: 16,
    fontWeight: "var(--font-weight-semibold)",
  },
});
