import React, { useState } from "react";
import { Autoplay, Navigation, Pagination } from "swiper/modules";
import { Swiper, SwiperSlide, useSwiper } from "swiper/react";
import DescriptionComponent from "../../../../global/common/DescriptionComponent";
import InfoIcon from "../../../../global/Icons/InfoIcon";
import { IProject } from "../../../../../types/global_types";
import { Title, Wrapper, Items, ArrowsWrapper } from "./styles";
import { ProjectCardItem } from "../../Crypto/styles";
import { useTranslation } from "i18n";

const items: Array<any> = [
  {
    _id: "676c8d00002b0ac8d197839e",
    projectType: "project",
    projectStatus: "active",
    isDuplicate: false,
    status: "Active",
    name: "Some token",
    tags: [],
    niche: "TKN",
    logo: "/9180.109833211869_3408.png",
    rating: "100",
    banner: "Banner text",
    fundraising: [],
    comparison: [],
    investors: [
      {
        _id: "668a341e05050dd380afcc31",
        projectStatus: "active",
        status: "active",
        name: "NEW FUND ",
        niche: "TEST",
        logo: "/47736.66087557094_img1.jpg",
        rating: "0",
        banner: "Text for IDO banner",
        investors: [
          {
            _id: "668a365505050dd380afcc68",
            projectStatus: "active",
            status: "active",
            name: "TEST PERSON",
            niche: "TEST",
            logo: "/68394.13084477752_img3.jpg",
            rating: "0",
            banner: "banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Sun Jul 07 2024 09:31:39 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-07T06:31:49.107Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "6682bd451bc03459fd36b813",
            projectStatus: "active",
            status: "active",
            name: "Person 2",
            niche: "Test",
            logo: "/15047.438677557424_img2.jpg",
            rating: "0",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Mon Jul 01 2024 17:29:11 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-01T14:29:25.220Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "661a45832337a87c6d4350b1",
            projectStatus: "active",
            status: "Ended",
            name: "Test person",
            niche: "Test",
            logo: "/52161.996970947075_img1.jpg",
            rating: "90",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: ["66827f06bba6ae236855bbd7", "662128717d6b86a5693586f4"],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "4500",
            lastFunding:
              "Sat Apr 13 2024 11:42:22 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2024-04-13T08:26:35.764Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 2,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: ["669ba639691dab684e193f5b"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "123",
            link: "",
            type: true,
          },
          {
            text: "sadfasdf",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "Test",
            link: "",
            type: true,
          },
          {
            text: "Test2",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "",
        lastFunding:
          "Sun Jul 07 2024 09:22:00 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        action: "Publication fund on Crypto page",
        actionType: "projects",
        actionDate: "2024-07-07T06:22:22.471Z",
        actionInitiator: "662153f47d6b86a569358c4d",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "Lorem test xax asdff...",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 1,
        type: "Type1",
      },
      {
        _id: "6619016c4ee8f99ed0f859cd",
        projectStatus: "active",
        status: "active",
        name: "New test",
        niche: "tttt",
        logo: "/85489.16223628906_img3.jpg",
        rating: "100",
        banner: "sharkRace club banner",
        investors: [
          {
            _id: "64de17a5c80905ef654ffddc",
            status: "Active",
            name: "Person 2",
            niche: "test",
            logo: "/62406.88262155936_img2.jpg",
            rating: "100",
            banner: "Text for IDO banner",
            investors: [
              {
                _id: "11",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
              {
                _id: "12",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
              {
                _id: "13",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
            ],
            team: [],
            advisors: [],
            partners: [],
            comments: ["64df58625b857731f4982f63"],
            redFlags: 0,
            redFlagsList: [
              {
                text: "sdfsadf",
                link: "",
                type: true,
              },
            ],
            greenFlagsList: [
              {
                text: "123123",
                link: "",
                type: true,
              },
            ],
            redStatus: false,
            totalRaised: "200",
            lastFunding:
              "Thu Aug 17 2023 15:50:26 GMT+0300 (Восточная Европа, летнее время)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2023-08-17T09:49:53.077Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "weasdf",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "64de0ecfc80905ef654ffd65",
            status: "Active",
            name: "Person test",
            niche: "niche",
            logo: "/1139.1325279500154_nimg1.jpg",
            rating: "100",
            banner: "Text for IDO banner",
            investors: [
              {
                _id: "13",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
              {
                _id: "12",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
              {
                _id: "11",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
            ],
            team: [],
            advisors: [],
            partners: [],
            comments: ["64df585b5b857731f4982f5c"],
            redFlags: 0,
            redFlagsList: [
              {
                text: "фывафыва",
                link: "",
                type: true,
              },
            ],
            greenFlagsList: [
              {
                text: "фывафыва",
                link: "",
                type: true,
              },
            ],
            redStatus: false,
            totalRaised: "123123",
            lastFunding:
              "Thu Aug 17 2023 15:12:37 GMT+0300 (Восточная Европа, летнее время)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2023-08-17T09:49:53.077Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "twasas",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 1,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: [
          "661bbe99b78ec0f1de63d0b0",
          "661a32f7ed73099d0158875e",
          "66195b56cf508a78a0c16c23",
          "66195b4bcf508a78a0c16c19",
        ],
        redFlags: 0,
        redFlagsList: [
          {
            text: "red",
            link: "",
            type: true,
          },
          {
            text: "red2",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "test2t",
            link: "",
            type: true,
          },
          {
            text: "test3",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "6000",
        lastFunding:
          "Fri Apr 12 2024 12:37:45 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        action: "Publication on crypto page",
        actionType: "projects",
        actionDate: "2024-04-12T09:39:56.944Z",
        actionInitiator: "660fdff3ef2a59da5b39eeff",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 6,
      },
      {
        _id: "668fea023601eda19a43ddd9",
        projectStatus: "active",
        status: "Active",
        name: "EARLYLAND FUND",
        niche: "TEST",
        logo: "/96907.76870135427_img2.jpg",
        rating: "100",
        banner: "Text for IDO banner",
        investors: [
          {
            _id: "668a365505050dd380afcc68",
            projectStatus: "active",
            status: "active",
            name: "TEST PERSON",
            niche: "TEST",
            logo: "/68394.13084477752_img3.jpg",
            rating: "0",
            banner: "banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Sun Jul 07 2024 09:31:39 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-07T06:31:49.107Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "6682bd451bc03459fd36b813",
            projectStatus: "active",
            status: "active",
            name: "Person 2",
            niche: "Test",
            logo: "/15047.438677557424_img2.jpg",
            rating: "0",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Mon Jul 01 2024 17:29:11 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-01T14:29:25.220Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "661a45832337a87c6d4350b1",
            projectStatus: "active",
            status: "Ended",
            name: "Test person",
            niche: "Test",
            logo: "/52161.996970947075_img1.jpg",
            rating: "90",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: ["66827f06bba6ae236855bbd7", "662128717d6b86a5693586f4"],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "4500",
            lastFunding:
              "Sat Apr 13 2024 11:42:22 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2024-04-13T08:26:35.764Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 2,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: ["669b63d8a9c25a61f4f9df45", "669b63d7a9c25a61f4f9df41"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "test2",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "5000",
        lastFunding:
          "Thu Jul 11 2024 17:19:29 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        actionType: "projects",
        actionDate: "2024-07-11T13:46:38.867Z",
        price: 12,
        lowPrice: 5,
        highPrice: 25,
        bio: "TestTestTestTestTestTestTestTestTestTestTestTestTest",
        marketCap: 2555,
        volume: 42,
        volumeGrowth: 14,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 2,
        type: "Type2",
      },
      {
        _id: "66d9afac0e998f736220b17e",
        projectStatus: "active",
        isDuplicate: false,
        originalEntityId: "66d9afac0e998f736220b17e",
        status: "Active",
        name: "TEST",
        niche: "TEST",
        logo: "/62951.71221056166_3408.png",
        rating: "88",
        banner: "TEST",
        investors: [],
        team: [],
        advisors: [],
        partners: [],
        comments: ["66dadf38cc71dbdf35bce1ac"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "123",
            link: "",
            type: true,
          },
          {
            text: "123123",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "test2123",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "",
        lastFunding:
          "Thu Sep 05 2024 16:11:23 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        actionType: "projects",
        actionDate: "2024-09-05T10:52:18.427Z",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "testtestetsttest",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 0,
      },
      {
        _id: "661a3e9aed73099d015888ba",
        projectStatus: "active",
        status: "Upcoming",
        name: "Fund test 2",
        niche: "Niche",
        logo: "/42583.13262457969_img1.jpg",
        rating: "100",
        banner: "Text for IDO banner",
        investors: [
          {
            _id: "661911b39bfd624014d792d2",
            projectStatus: "active",
            status: "active",
            name: "sdf",
            niche: "sdf",
            logo: "/93941.56960359012_img1.jpg",
            rating: "90",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: ["661a3bd5ed73099d01588821"],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "2500",
            lastFunding:
              "Fri Apr 12 2024 13:48:48 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication on Crypto page",
            actionType: "projects",
            actionDate: "2024-04-12T10:49:23.025Z",
            actionInitiator: "660fdff3ef2a59da5b39eeff",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 1,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: [
          "6621611b7d6b86a569358f15",
          "662161187d6b86a569358f11",
          "662128807d6b86a569358707",
          "661ba3aab78ec0f1de63cdd2",
        ],
        redFlags: 0,
        redFlagsList: [
          {
            text: "test 2",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "4500",
        lastFunding:
          "Sat Apr 13 2024 11:12:50 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        actionType: "projects",
        actionDate: "2024-04-13T07:16:32.346Z",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "testtest",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 4,
      },
    ],
    team: [],
    advisors: [],
    partners: [],
    comments: ["67a96e8258e9b2407189f19e"],
    redFlags: 0,
    redFlagsList: [
      {
        text: "test",
        link: "",
        type: true,
      },
      {
        text: "test2",
        link: "",
        type: true,
      },
    ],
    greenFlagsList: [],
    redStatus: true,
    totalRaised: 50000,
    lastFunding:
      "Thu Dec 26 2024 00:02:20 GMT+0200 (за східноєвропейським стандартним часом)",
    fullness: "75%",
    actionType: "projects",
    actionDate: "2024-12-25T22:02:01.086Z",
    price: 0,
    priceBTC: 0,
    priceChange: 0,
    lowPrice: 0,
    highPrice: 0,
    bio: "",
    marketCap: 0,
    volume: 0,
    volume24h: 0,
    volume24hChange: 0,
    circulatingSupply: 0,
    volumeGrowth: 0,
    dominance: 0,
    fullyDilutedMarketCap: 0,
    totalSupply: 0,
    totalForSale: 0,
    totalAllocation: [],
    volumeAndMarketCap: 0,
    isIdea: false,
    greenZone: 0,
    yellowZone: 0,
    nftStakeNeed: 0,
    comission: 0,
    mediaComission: 0,
    media: [],
    poolActive: true,
    isMainProject: true,
    isClaimStart: false,
    isRefunded: false,
    recommendations: [],
    faq: [],
    descriptionImage: "",
    fundingGoal: 0,
    isETH: false,
    createdAt: "2024-12-25T22:53:52.334Z",
    __v: 1,
    twitterData: {},
  },
  {
    _id: "676c8e2c002b0ac8d19784e9",
    projectType: "project",
    projectStatus: "active",
    isDuplicate: false,
    status: "Active",
    name: "NEW TOKEN",
    tags: [],
    niche: "SOME",
    logo: "/5357.077768231667_630c5fcaf8184351dc5c6ee5.png",
    rating: "100",
    banner: "Text for IDO banner",
    fundraising: [],
    comparison: [],
    investors: [
      {
        _id: "668fea023601eda19a43ddd9",
        projectStatus: "active",
        status: "Active",
        name: "EARLYLAND FUND",
        niche: "TEST",
        logo: "/96907.76870135427_img2.jpg",
        rating: "100",
        banner: "Text for IDO banner",
        investors: [
          {
            _id: "668a365505050dd380afcc68",
            projectStatus: "active",
            status: "active",
            name: "TEST PERSON",
            niche: "TEST",
            logo: "/68394.13084477752_img3.jpg",
            rating: "0",
            banner: "banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Sun Jul 07 2024 09:31:39 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-07T06:31:49.107Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "6682bd451bc03459fd36b813",
            projectStatus: "active",
            status: "active",
            name: "Person 2",
            niche: "Test",
            logo: "/15047.438677557424_img2.jpg",
            rating: "0",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Mon Jul 01 2024 17:29:11 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-01T14:29:25.220Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "661a45832337a87c6d4350b1",
            projectStatus: "active",
            status: "Ended",
            name: "Test person",
            niche: "Test",
            logo: "/52161.996970947075_img1.jpg",
            rating: "90",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: ["66827f06bba6ae236855bbd7", "662128717d6b86a5693586f4"],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "4500",
            lastFunding:
              "Sat Apr 13 2024 11:42:22 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2024-04-13T08:26:35.764Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 2,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: ["669b63d8a9c25a61f4f9df45", "669b63d7a9c25a61f4f9df41"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "test2",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "5000",
        lastFunding:
          "Thu Jul 11 2024 17:19:29 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        actionType: "projects",
        actionDate: "2024-07-11T13:46:38.867Z",
        price: 12,
        lowPrice: 5,
        highPrice: 25,
        bio: "TestTestTestTestTestTestTestTestTestTestTestTestTest",
        marketCap: 2555,
        volume: 42,
        volumeGrowth: 14,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 2,
        type: "Type2",
      },
      {
        _id: "668a341e05050dd380afcc31",
        projectStatus: "active",
        status: "active",
        name: "NEW FUND ",
        niche: "TEST",
        logo: "/47736.66087557094_img1.jpg",
        rating: "0",
        banner: "Text for IDO banner",
        investors: [
          {
            _id: "668a365505050dd380afcc68",
            projectStatus: "active",
            status: "active",
            name: "TEST PERSON",
            niche: "TEST",
            logo: "/68394.13084477752_img3.jpg",
            rating: "0",
            banner: "banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Sun Jul 07 2024 09:31:39 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-07T06:31:49.107Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "6682bd451bc03459fd36b813",
            projectStatus: "active",
            status: "active",
            name: "Person 2",
            niche: "Test",
            logo: "/15047.438677557424_img2.jpg",
            rating: "0",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Mon Jul 01 2024 17:29:11 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-01T14:29:25.220Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "661a45832337a87c6d4350b1",
            projectStatus: "active",
            status: "Ended",
            name: "Test person",
            niche: "Test",
            logo: "/52161.996970947075_img1.jpg",
            rating: "90",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: ["66827f06bba6ae236855bbd7", "662128717d6b86a5693586f4"],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "4500",
            lastFunding:
              "Sat Apr 13 2024 11:42:22 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2024-04-13T08:26:35.764Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 2,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: ["669ba639691dab684e193f5b"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "123",
            link: "",
            type: true,
          },
          {
            text: "sadfasdf",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "Test",
            link: "",
            type: true,
          },
          {
            text: "Test2",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "",
        lastFunding:
          "Sun Jul 07 2024 09:22:00 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        action: "Publication fund on Crypto page",
        actionType: "projects",
        actionDate: "2024-07-07T06:22:22.471Z",
        actionInitiator: "662153f47d6b86a569358c4d",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "Lorem test xax asdff...",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 1,
        type: "Type1",
      },
    ],
    team: [],
    advisors: [],
    partners: [],
    comments: [],
    redFlags: 0,
    redFlagsList: [],
    greenFlagsList: [],
    redStatus: false,
    totalRaised: 123123,
    lastFunding:
      "Thu Dec 26 2024 00:54:30 GMT+0200 (за східноєвропейським стандартним часом)",
    fullness: "75%",
    actionType: "projects",
    actionDate: "2024-12-25T22:02:01.086Z",
    price: 0,
    priceBTC: 0,
    priceChange: 0,
    lowPrice: 0,
    highPrice: 0,
    bio: "",
    marketCap: 0,
    volume: 0,
    volume24h: 0,
    volume24hChange: 0,
    circulatingSupply: 0,
    volumeGrowth: 0,
    dominance: 0,
    fullyDilutedMarketCap: 0,
    totalSupply: 0,
    totalForSale: 0,
    totalAllocation: [],
    volumeAndMarketCap: 0,
    isIdea: false,
    greenZone: 0,
    yellowZone: 0,
    nftStakeNeed: 0,
    comission: 0,
    mediaComission: 0,
    media: [],
    poolActive: true,
    isMainProject: true,
    isClaimStart: false,
    isRefunded: false,
    recommendations: [],
    faq: [],
    descriptionImage: "",
    fundingGoal: 0,
    isETH: false,
    createdAt: "2024-12-25T22:58:52.640Z",
    __v: 0,
  },
  {
    _id: "676c8e49002b0ac8d1978508",
    projectType: "project",
    projectStatus: "active",
    isDuplicate: false,
    status: "Active",
    name: "TKN",
    tags: [],
    niche: "Test",
    logo: "/37416.52183068471_74587.27748792653_112479764.png",
    rating: "100",
    banner: "Text for IDO banner",
    fundraising: [],
    comparison: [],
    investors: [
      {
        _id: "66d9afac0e998f736220b17e",
        projectStatus: "active",
        isDuplicate: false,
        originalEntityId: "66d9afac0e998f736220b17e",
        status: "Active",
        name: "TEST",
        niche: "TEST",
        logo: "/62951.71221056166_3408.png",
        rating: "88",
        banner: "TEST",
        investors: [],
        team: [],
        advisors: [],
        partners: [],
        comments: ["66dadf38cc71dbdf35bce1ac"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "123",
            link: "",
            type: true,
          },
          {
            text: "123123",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "test2123",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "",
        lastFunding:
          "Thu Sep 05 2024 16:11:23 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        actionType: "projects",
        actionDate: "2024-09-05T10:52:18.427Z",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "testtestetsttest",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 0,
      },
    ],
    team: [],
    advisors: [],
    partners: [],
    comments: [],
    redFlags: 0,
    redFlagsList: [],
    greenFlagsList: [],
    redStatus: false,
    totalRaised: 123123,
    lastFunding:
      "Thu Dec 26 2024 00:58:53 GMT+0200 (за східноєвропейським стандартним часом)",
    fullness: "75%",
    actionType: "projects",
    actionDate: "2024-12-25T22:02:01.086Z",
    price: 0,
    priceBTC: 0,
    priceChange: 0,
    lowPrice: 0,
    highPrice: 0,
    bio: "",
    marketCap: 0,
    volume: 0,
    volume24h: 0,
    volume24hChange: 0,
    circulatingSupply: 0,
    volumeGrowth: 0,
    dominance: 0,
    fullyDilutedMarketCap: 0,
    totalSupply: 0,
    totalForSale: 0,
    totalAllocation: [],
    volumeAndMarketCap: 0,
    isIdea: false,
    greenZone: 0,
    yellowZone: 0,
    nftStakeNeed: 0,
    comission: 0,
    mediaComission: 0,
    media: [],
    poolActive: true,
    isMainProject: true,
    isClaimStart: false,
    isRefunded: false,
    recommendations: [],
    faq: [],
    descriptionImage: "",
    fundingGoal: 0,
    isETH: false,
    createdAt: "2024-12-25T22:59:21.977Z",
    __v: 0,
  },
  {
    _id: "676c8d00002b0ac8d197839e",
    projectType: "project",
    projectStatus: "active",
    isDuplicate: false,
    status: "Active",
    name: "Some token",
    tags: [],
    niche: "TKN",
    logo: "/9180.109833211869_3408.png",
    rating: "100",
    banner: "Banner text",
    fundraising: [],
    comparison: [],
    investors: [
      {
        _id: "668a341e05050dd380afcc31",
        projectStatus: "active",
        status: "active",
        name: "NEW FUND ",
        niche: "TEST",
        logo: "/47736.66087557094_img1.jpg",
        rating: "0",
        banner: "Text for IDO banner",
        investors: [
          {
            _id: "668a365505050dd380afcc68",
            projectStatus: "active",
            status: "active",
            name: "TEST PERSON",
            niche: "TEST",
            logo: "/68394.13084477752_img3.jpg",
            rating: "0",
            banner: "banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Sun Jul 07 2024 09:31:39 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-07T06:31:49.107Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "6682bd451bc03459fd36b813",
            projectStatus: "active",
            status: "active",
            name: "Person 2",
            niche: "Test",
            logo: "/15047.438677557424_img2.jpg",
            rating: "0",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Mon Jul 01 2024 17:29:11 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-01T14:29:25.220Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "661a45832337a87c6d4350b1",
            projectStatus: "active",
            status: "Ended",
            name: "Test person",
            niche: "Test",
            logo: "/52161.996970947075_img1.jpg",
            rating: "90",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: ["66827f06bba6ae236855bbd7", "662128717d6b86a5693586f4"],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "4500",
            lastFunding:
              "Sat Apr 13 2024 11:42:22 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2024-04-13T08:26:35.764Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 2,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: ["669ba639691dab684e193f5b"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "123",
            link: "",
            type: true,
          },
          {
            text: "sadfasdf",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "Test",
            link: "",
            type: true,
          },
          {
            text: "Test2",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "",
        lastFunding:
          "Sun Jul 07 2024 09:22:00 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        action: "Publication fund on Crypto page",
        actionType: "projects",
        actionDate: "2024-07-07T06:22:22.471Z",
        actionInitiator: "662153f47d6b86a569358c4d",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "Lorem test xax asdff...",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 1,
        type: "Type1",
      },
      {
        _id: "6619016c4ee8f99ed0f859cd",
        projectStatus: "active",
        status: "active",
        name: "New test",
        niche: "tttt",
        logo: "/85489.16223628906_img3.jpg",
        rating: "100",
        banner: "sharkRace club banner",
        investors: [
          {
            _id: "64de17a5c80905ef654ffddc",
            status: "Active",
            name: "Person 2",
            niche: "test",
            logo: "/62406.88262155936_img2.jpg",
            rating: "100",
            banner: "Text for IDO banner",
            investors: [
              {
                _id: "11",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
              {
                _id: "12",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
              {
                _id: "13",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
            ],
            team: [],
            advisors: [],
            partners: [],
            comments: ["64df58625b857731f4982f63"],
            redFlags: 0,
            redFlagsList: [
              {
                text: "sdfsadf",
                link: "",
                type: true,
              },
            ],
            greenFlagsList: [
              {
                text: "123123",
                link: "",
                type: true,
              },
            ],
            redStatus: false,
            totalRaised: "200",
            lastFunding:
              "Thu Aug 17 2023 15:50:26 GMT+0300 (Восточная Европа, летнее время)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2023-08-17T09:49:53.077Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "weasdf",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "64de0ecfc80905ef654ffd65",
            status: "Active",
            name: "Person test",
            niche: "niche",
            logo: "/1139.1325279500154_nimg1.jpg",
            rating: "100",
            banner: "Text for IDO banner",
            investors: [
              {
                _id: "13",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
              {
                _id: "12",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
              {
                _id: "11",
                img: "/static/media/avatar.934339d98b117001e1d3.png",
                name: "Dr. Laurent El Ghaul",
                selected: true,
              },
            ],
            team: [],
            advisors: [],
            partners: [],
            comments: ["64df585b5b857731f4982f5c"],
            redFlags: 0,
            redFlagsList: [
              {
                text: "фывафыва",
                link: "",
                type: true,
              },
            ],
            greenFlagsList: [
              {
                text: "фывафыва",
                link: "",
                type: true,
              },
            ],
            redStatus: false,
            totalRaised: "123123",
            lastFunding:
              "Thu Aug 17 2023 15:12:37 GMT+0300 (Восточная Европа, летнее время)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2023-08-17T09:49:53.077Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "twasas",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 1,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: [
          "661bbe99b78ec0f1de63d0b0",
          "661a32f7ed73099d0158875e",
          "66195b56cf508a78a0c16c23",
          "66195b4bcf508a78a0c16c19",
        ],
        redFlags: 0,
        redFlagsList: [
          {
            text: "red",
            link: "",
            type: true,
          },
          {
            text: "red2",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "test2t",
            link: "",
            type: true,
          },
          {
            text: "test3",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "6000",
        lastFunding:
          "Fri Apr 12 2024 12:37:45 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        action: "Publication on crypto page",
        actionType: "projects",
        actionDate: "2024-04-12T09:39:56.944Z",
        actionInitiator: "660fdff3ef2a59da5b39eeff",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 6,
      },
      {
        _id: "668fea023601eda19a43ddd9",
        projectStatus: "active",
        status: "Active",
        name: "EARLYLAND FUND",
        niche: "TEST",
        logo: "/96907.76870135427_img2.jpg",
        rating: "100",
        banner: "Text for IDO banner",
        investors: [
          {
            _id: "668a365505050dd380afcc68",
            projectStatus: "active",
            status: "active",
            name: "TEST PERSON",
            niche: "TEST",
            logo: "/68394.13084477752_img3.jpg",
            rating: "0",
            banner: "banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Sun Jul 07 2024 09:31:39 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-07T06:31:49.107Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "6682bd451bc03459fd36b813",
            projectStatus: "active",
            status: "active",
            name: "Person 2",
            niche: "Test",
            logo: "/15047.438677557424_img2.jpg",
            rating: "0",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Mon Jul 01 2024 17:29:11 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-01T14:29:25.220Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "661a45832337a87c6d4350b1",
            projectStatus: "active",
            status: "Ended",
            name: "Test person",
            niche: "Test",
            logo: "/52161.996970947075_img1.jpg",
            rating: "90",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: ["66827f06bba6ae236855bbd7", "662128717d6b86a5693586f4"],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "4500",
            lastFunding:
              "Sat Apr 13 2024 11:42:22 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2024-04-13T08:26:35.764Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 2,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: ["669b63d8a9c25a61f4f9df45", "669b63d7a9c25a61f4f9df41"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "test2",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "5000",
        lastFunding:
          "Thu Jul 11 2024 17:19:29 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        actionType: "projects",
        actionDate: "2024-07-11T13:46:38.867Z",
        price: 12,
        lowPrice: 5,
        highPrice: 25,
        bio: "TestTestTestTestTestTestTestTestTestTestTestTestTest",
        marketCap: 2555,
        volume: 42,
        volumeGrowth: 14,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 2,
        type: "Type2",
      },
      {
        _id: "66d9afac0e998f736220b17e",
        projectStatus: "active",
        isDuplicate: false,
        originalEntityId: "66d9afac0e998f736220b17e",
        status: "Active",
        name: "TEST",
        niche: "TEST",
        logo: "/62951.71221056166_3408.png",
        rating: "88",
        banner: "TEST",
        investors: [],
        team: [],
        advisors: [],
        partners: [],
        comments: ["66dadf38cc71dbdf35bce1ac"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "123",
            link: "",
            type: true,
          },
          {
            text: "123123",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "test2123",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "",
        lastFunding:
          "Thu Sep 05 2024 16:11:23 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        actionType: "projects",
        actionDate: "2024-09-05T10:52:18.427Z",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "testtestetsttest",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 0,
      },
      {
        _id: "661a3e9aed73099d015888ba",
        projectStatus: "active",
        status: "Upcoming",
        name: "Fund test 2",
        niche: "Niche",
        logo: "/42583.13262457969_img1.jpg",
        rating: "100",
        banner: "Text for IDO banner",
        investors: [
          {
            _id: "661911b39bfd624014d792d2",
            projectStatus: "active",
            status: "active",
            name: "sdf",
            niche: "sdf",
            logo: "/93941.56960359012_img1.jpg",
            rating: "90",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: ["661a3bd5ed73099d01588821"],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "2500",
            lastFunding:
              "Fri Apr 12 2024 13:48:48 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication on Crypto page",
            actionType: "projects",
            actionDate: "2024-04-12T10:49:23.025Z",
            actionInitiator: "660fdff3ef2a59da5b39eeff",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 1,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: [
          "6621611b7d6b86a569358f15",
          "662161187d6b86a569358f11",
          "662128807d6b86a569358707",
          "661ba3aab78ec0f1de63cdd2",
        ],
        redFlags: 0,
        redFlagsList: [
          {
            text: "test 2",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "4500",
        lastFunding:
          "Sat Apr 13 2024 11:12:50 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        actionType: "projects",
        actionDate: "2024-04-13T07:16:32.346Z",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "testtest",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 4,
      },
    ],
    team: [],
    advisors: [],
    partners: [],
    comments: ["67a96e8258e9b2407189f19e"],
    redFlags: 0,
    redFlagsList: [
      {
        text: "test",
        link: "",
        type: true,
      },
      {
        text: "test2",
        link: "",
        type: true,
      },
    ],
    greenFlagsList: [],
    redStatus: true,
    totalRaised: 50000,
    lastFunding:
      "Thu Dec 26 2024 00:02:20 GMT+0200 (за східноєвропейським стандартним часом)",
    fullness: "75%",
    actionType: "projects",
    actionDate: "2024-12-25T22:02:01.086Z",
    price: 0,
    priceBTC: 0,
    priceChange: 0,
    lowPrice: 0,
    highPrice: 0,
    bio: "",
    marketCap: 0,
    volume: 0,
    volume24h: 0,
    volume24hChange: 0,
    circulatingSupply: 0,
    volumeGrowth: 0,
    dominance: 0,
    fullyDilutedMarketCap: 0,
    totalSupply: 0,
    totalForSale: 0,
    totalAllocation: [],
    volumeAndMarketCap: 0,
    isIdea: false,
    greenZone: 0,
    yellowZone: 0,
    nftStakeNeed: 0,
    comission: 0,
    mediaComission: 0,
    media: [],
    poolActive: true,
    isMainProject: true,
    isClaimStart: false,
    isRefunded: false,
    recommendations: [],
    faq: [],
    descriptionImage: "",
    fundingGoal: 0,
    isETH: false,
    createdAt: "2024-12-25T22:53:52.334Z",
    __v: 1,
    twitterData: {},
  },
  {
    _id: "676c8e2c002b0ac8d19784e9",
    projectType: "project",
    projectStatus: "active",
    isDuplicate: false,
    status: "Active",
    name: "NEW TOKEN",
    tags: [],
    niche: "SOME",
    logo: "/5357.077768231667_630c5fcaf8184351dc5c6ee5.png",
    rating: "100",
    banner: "Text for IDO banner",
    fundraising: [],
    comparison: [],
    investors: [
      {
        _id: "668fea023601eda19a43ddd9",
        projectStatus: "active",
        status: "Active",
        name: "EARLYLAND FUND",
        niche: "TEST",
        logo: "/96907.76870135427_img2.jpg",
        rating: "100",
        banner: "Text for IDO banner",
        investors: [
          {
            _id: "668a365505050dd380afcc68",
            projectStatus: "active",
            status: "active",
            name: "TEST PERSON",
            niche: "TEST",
            logo: "/68394.13084477752_img3.jpg",
            rating: "0",
            banner: "banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Sun Jul 07 2024 09:31:39 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-07T06:31:49.107Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "6682bd451bc03459fd36b813",
            projectStatus: "active",
            status: "active",
            name: "Person 2",
            niche: "Test",
            logo: "/15047.438677557424_img2.jpg",
            rating: "0",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Mon Jul 01 2024 17:29:11 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-01T14:29:25.220Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "661a45832337a87c6d4350b1",
            projectStatus: "active",
            status: "Ended",
            name: "Test person",
            niche: "Test",
            logo: "/52161.996970947075_img1.jpg",
            rating: "90",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: ["66827f06bba6ae236855bbd7", "662128717d6b86a5693586f4"],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "4500",
            lastFunding:
              "Sat Apr 13 2024 11:42:22 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2024-04-13T08:26:35.764Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 2,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: ["669b63d8a9c25a61f4f9df45", "669b63d7a9c25a61f4f9df41"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "test2",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "5000",
        lastFunding:
          "Thu Jul 11 2024 17:19:29 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        actionType: "projects",
        actionDate: "2024-07-11T13:46:38.867Z",
        price: 12,
        lowPrice: 5,
        highPrice: 25,
        bio: "TestTestTestTestTestTestTestTestTestTestTestTestTest",
        marketCap: 2555,
        volume: 42,
        volumeGrowth: 14,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 2,
        type: "Type2",
      },
      {
        _id: "668a341e05050dd380afcc31",
        projectStatus: "active",
        status: "active",
        name: "NEW FUND ",
        niche: "TEST",
        logo: "/47736.66087557094_img1.jpg",
        rating: "0",
        banner: "Text for IDO banner",
        investors: [
          {
            _id: "668a365505050dd380afcc68",
            projectStatus: "active",
            status: "active",
            name: "TEST PERSON",
            niche: "TEST",
            logo: "/68394.13084477752_img3.jpg",
            rating: "0",
            banner: "banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Sun Jul 07 2024 09:31:39 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-07T06:31:49.107Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "6682bd451bc03459fd36b813",
            projectStatus: "active",
            status: "active",
            name: "Person 2",
            niche: "Test",
            logo: "/15047.438677557424_img2.jpg",
            rating: "0",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: [],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "",
            lastFunding:
              "Mon Jul 01 2024 17:29:11 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            action: "Publication person on Crypto page",
            actionType: "projects",
            actionDate: "2024-07-01T14:29:25.220Z",
            actionInitiator: "662153f47d6b86a569358c4d",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 0,
            selected: true,
          },
          {
            _id: "661a45832337a87c6d4350b1",
            projectStatus: "active",
            status: "Ended",
            name: "Test person",
            niche: "Test",
            logo: "/52161.996970947075_img1.jpg",
            rating: "90",
            banner: "Text for IDO banner",
            investors: [],
            team: [],
            advisors: [],
            partners: [],
            comments: ["66827f06bba6ae236855bbd7", "662128717d6b86a5693586f4"],
            redFlags: 0,
            redFlagsList: [],
            greenFlagsList: [],
            redStatus: false,
            totalRaised: "4500",
            lastFunding:
              "Sat Apr 13 2024 11:42:22 GMT+0300 (за східноєвропейським літнім часом)",
            fullness: "75%",
            actionType: "projects",
            actionDate: "2024-04-13T08:26:35.764Z",
            price: 0,
            lowPrice: 0,
            highPrice: 0,
            bio: "",
            marketCap: 0,
            volume: 0,
            volumeGrowth: 0,
            totalSupply: 0,
            totalForSale: 0,
            totalAllocation: [],
            __v: 2,
            selected: true,
          },
        ],
        team: [],
        advisors: [],
        partners: [],
        comments: ["669ba639691dab684e193f5b"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "123",
            link: "",
            type: true,
          },
          {
            text: "sadfasdf",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "Test",
            link: "",
            type: true,
          },
          {
            text: "Test2",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "",
        lastFunding:
          "Sun Jul 07 2024 09:22:00 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        action: "Publication fund on Crypto page",
        actionType: "projects",
        actionDate: "2024-07-07T06:22:22.471Z",
        actionInitiator: "662153f47d6b86a569358c4d",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "Lorem test xax asdff...",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 1,
        type: "Type1",
      },
    ],
    team: [],
    advisors: [],
    partners: [],
    comments: [],
    redFlags: 0,
    redFlagsList: [],
    greenFlagsList: [],
    redStatus: false,
    totalRaised: 123123,
    lastFunding:
      "Thu Dec 26 2024 00:54:30 GMT+0200 (за східноєвропейським стандартним часом)",
    fullness: "75%",
    actionType: "projects",
    actionDate: "2024-12-25T22:02:01.086Z",
    price: 0,
    priceBTC: 0,
    priceChange: 0,
    lowPrice: 0,
    highPrice: 0,
    bio: "",
    marketCap: 0,
    volume: 0,
    volume24h: 0,
    volume24hChange: 0,
    circulatingSupply: 0,
    volumeGrowth: 0,
    dominance: 0,
    fullyDilutedMarketCap: 0,
    totalSupply: 0,
    totalForSale: 0,
    totalAllocation: [],
    volumeAndMarketCap: 0,
    isIdea: false,
    greenZone: 0,
    yellowZone: 0,
    nftStakeNeed: 0,
    comission: 0,
    mediaComission: 0,
    media: [],
    poolActive: true,
    isMainProject: true,
    isClaimStart: false,
    isRefunded: false,
    recommendations: [],
    faq: [],
    descriptionImage: "",
    fundingGoal: 0,
    isETH: false,
    createdAt: "2024-12-25T22:58:52.640Z",
    __v: 0,
  },
  {
    _id: "676c8e49002b0ac8d1978508",
    projectType: "project",
    projectStatus: "active",
    isDuplicate: false,
    status: "Active",
    name: "TKN",
    tags: [],
    niche: "Test",
    logo: "/37416.52183068471_74587.27748792653_112479764.png",
    rating: "100",
    banner: "Text for IDO banner",
    fundraising: [],
    comparison: [],
    investors: [
      {
        _id: "66d9afac0e998f736220b17e",
        projectStatus: "active",
        isDuplicate: false,
        originalEntityId: "66d9afac0e998f736220b17e",
        status: "Active",
        name: "TEST",
        niche: "TEST",
        logo: "/62951.71221056166_3408.png",
        rating: "88",
        banner: "TEST",
        investors: [],
        team: [],
        advisors: [],
        partners: [],
        comments: ["66dadf38cc71dbdf35bce1ac"],
        redFlags: 0,
        redFlagsList: [
          {
            text: "123",
            link: "",
            type: true,
          },
          {
            text: "123123",
            link: "",
            type: true,
          },
        ],
        greenFlagsList: [
          {
            text: "test",
            link: "",
            type: true,
          },
          {
            text: "test2123",
            link: "",
            type: true,
          },
        ],
        redStatus: false,
        totalRaised: "",
        lastFunding:
          "Thu Sep 05 2024 16:11:23 GMT+0300 (за східноєвропейським літнім часом)",
        fullness: "75%",
        actionType: "projects",
        actionDate: "2024-09-05T10:52:18.427Z",
        price: 0,
        lowPrice: 0,
        highPrice: 0,
        bio: "testtestetsttest",
        marketCap: 0,
        volume: 0,
        volumeGrowth: 0,
        totalSupply: 0,
        totalForSale: 0,
        totalAllocation: [],
        __v: 0,
      },
    ],
    team: [],
    advisors: [],
    partners: [],
    comments: [],
    redFlags: 0,
    redFlagsList: [],
    greenFlagsList: [],
    redStatus: false,
    totalRaised: 123123,
    lastFunding:
      "Thu Dec 26 2024 00:58:53 GMT+0200 (за східноєвропейським стандартним часом)",
    fullness: "75%",
    actionType: "projects",
    actionDate: "2024-12-25T22:02:01.086Z",
    price: 0,
    priceBTC: 0,
    priceChange: 0,
    lowPrice: 0,
    highPrice: 0,
    bio: "",
    marketCap: 0,
    volume: 0,
    volume24h: 0,
    volume24hChange: 0,
    circulatingSupply: 0,
    volumeGrowth: 0,
    dominance: 0,
    fullyDilutedMarketCap: 0,
    totalSupply: 0,
    totalForSale: 0,
    totalAllocation: [],
    volumeAndMarketCap: 0,
    isIdea: false,
    greenZone: 0,
    yellowZone: 0,
    nftStakeNeed: 0,
    comission: 0,
    mediaComission: 0,
    media: [],
    poolActive: true,
    isMainProject: true,
    isClaimStart: false,
    isRefunded: false,
    recommendations: [],
    faq: [],
    descriptionImage: "",
    fundingGoal: 0,
    isETH: false,
    createdAt: "2024-12-25T22:59:21.977Z",
    __v: 0,
  },
];

const FomoSpotlight = () => {
  const { translateText } = useTranslation();
  const [swiper, setSwiper] = useState<any>(null);
  const [isDescription, setIsDescription] = useState<boolean>(false);
  const [isHover, setIsHover] = useState<boolean>(false);

  return (
    <Wrapper>
      <Title>
        <span className="title-wrapper">{translateText("FOMO Spotlight")}</span>
        <button
          onMouseEnter={() => setIsDescription(true)}
          onMouseLeave={() => setIsDescription(false)}
        >
          <InfoIcon />
        </button>
        <DescriptionComponent
          className="eralash-description"
          isVisible={isDescription}
          date={new Date()}
          isDate={false}
          text={`<div>${translateText(
            "Featured projects with premium visibility. These listings receive enhanced exposure within the FOMO ecosystem for greater reach and engagement"
          )}</div>`}
        />
      </Title>
      <Items
        onMouseEnter={() => setIsHover(true)}
        onMouseLeave={() => setIsHover(false)}
      >
        <Swiper
          modules={[Autoplay, Navigation]}
          spaceBetween={20}
          slidesPerView={3}
          onSwiper={setSwiper}
          autoplay={{
            delay: 3000,
            disableOnInteraction: false,
          }}
          breakpoints={{
            320: {
              slidesPerView: 1,
            },
            768: {
              slidesPerView: 2,
            },
            1024: {
              slidesPerView: 3,
            },
          }}
          loop
        >
          {items.map((item: IProject, i: number) => (
            <SwiperSlide key={`${item._id}${i}`}>
              <ProjectCardItem type="unlocking" cardData={item} />
            </SwiperSlide>
          ))}
        </Swiper>
        {isHover && swiper && (
          <ArrowsWrapper>
            <button onClick={() => swiper.slidePrev()}>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
              >
                <path
                  d="M15 4.5L7.5 12L15 19.5"
                  stroke="#738094"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </button>
            <button onClick={() => swiper.slideNext()}>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
              >
                <path
                  d="M9 4.5L16.5 12L9 19.5"
                  stroke="#738094"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </button>
          </ArrowsWrapper>
        )}
      </Items>
    </Wrapper>
  );
};

export default FomoSpotlight;
