import { createUseStyles } from "react-jss";

export const useStyles = createUseStyles({
  page: {
    padding: "24px",
    color: "var(--color-text-primary)",
    background: "var(--color-surface-muted)",
    minHeight: "100vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "16px",
    "& h1": {
      margin: [0, 0, 6, 0],
      fontSize: "26px",
      lineHeight: "32px",
    },
    "& p": {
      margin: 0,
      color: "var(--color-text-muted)",
      fontSize: "14px",
      lineHeight: "20px",
      maxWidth: "760px",
    },
  },
  actions: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  button: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "36px",
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    padding: "8px 12px",
    background: "var(--color-white)",
    color: "var(--color-text-primary)",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    whiteSpace: "nowrap",
    boxShadow: "0 3px 8px rgba(15, 23, 42, 0.08)",
    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.55,
    },
  },
  buttonLink: {
    textDecoration: "none",
  },
  primaryButton: {
    border: "none",
    background: "var(--color-primary)",
    color: "var(--color-white)",
  },
  dangerButton: {
    border: "none",
    background: "var(--color-danger)",
    color: "var(--color-white)",
  },
  warningButton: {
    border: "none",
    background: "#F4A11E",
    color: "var(--color-white)",
  },
  quickFilters: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    marginBottom: "14px",
  },
  flowNotice: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    flexWrap: "wrap",
    border: "1px solid #BFE8DD",
    borderRadius: "8px",
    background: "#F0FBF7",
    color: "#126B59",
    padding: "10px 12px",
    marginBottom: "14px",
    fontSize: "13px",
    lineHeight: "18px",
    fontWeight: "var(--font-weight-medium)",
    "& a": {
      color: "#04745E",
      fontWeight: "var(--font-weight-semibold)",
      textDecoration: "none",
      whiteSpace: "nowrap",
    },
  },
  warningNotice: {
    borderColor: "#F7D9A2",
    background: "#FFF8EB",
    color: "#7A4F0D",
    "& a": {
      color: "#8A590B",
    },
  },
  quickFilter: {
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    background: "var(--color-white)",
    color: "#445066",
    minHeight: "34px",
    padding: "7px 10px",
    fontSize: "12px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    boxShadow: "0 5px 12px rgba(15, 23, 42, 0.06)",
  },
  quickFilterActive: {
    borderColor: "var(--color-primary)",
    background: "var(--color-primary-soft)",
    color: "#04745E",
  },
  tabs: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    marginBottom: "14px",
  },
  tab: {
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    background: "var(--color-white)",
    color: "#445066",
    padding: "8px 10px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    minHeight: "36px",
    boxShadow: "0 5px 12px rgba(15, 23, 42, 0.06)",
  },
  activeTab: {
    background: "var(--color-text-primary)",
    borderColor: "var(--color-text-primary)",
    color: "var(--color-white)",
  },
  filters: {
    display: "grid",
    gridTemplateColumns: "repeat(5, minmax(120px, 1fr)) minmax(220px, 1.5fr)",
    gap: "10px",
    marginBottom: "14px",
    "@media (max-width: 1100px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
    },
    "& select, & input": {
      width: "100%",
      minHeight: "38px",
      border: "1px solid var(--color-border)",
      borderRadius: "8px",
      background: "var(--color-white)",
      color: "var(--color-text-primary)",
      padding: "8px 10px",
      fontSize: "13px",
      boxSizing: "border-box",
    },
  },
  summary: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "10px",
    marginBottom: "14px",
  },
  metric: {
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    padding: "10px 12px",
    background: "var(--color-white)",
    boxShadow: "0 12px 26px rgba(15, 23, 42, 0.08)",
    "& span": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: "12px",
      marginBottom: "4px",
    },
    "& strong": {
      display: "block",
      fontSize: "20px",
      lineHeight: "24px",
    },
  },
  tableWrap: {
    overflowX: "auto",
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    background: "var(--color-white)",
  },
  bulkToolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    background: "var(--color-white)",
    padding: "10px 12px",
    marginBottom: "12px",
    "& span": {
      color: "#445066",
      fontSize: "13px",
      fontWeight: "var(--font-weight-semibold)",
    },
  },
  bulkNote: {
    minHeight: "36px",
    minWidth: "260px",
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    padding: "8px 10px",
    fontSize: "13px",
    boxSizing: "border-box",
    "@media (max-width: 640px)": {
      minWidth: "100%",
    },
  },
  table: {
    width: "100%",
    minWidth: "1080px",
    borderCollapse: "collapse",
    "& th": {
      textAlign: "left",
      color: "var(--color-text-muted)",
      fontSize: "12px",
      lineHeight: "16px",
      padding: "10px",
      borderBottom: "1px solid #EEF2F6",
      background: "#FCFDFE",
      whiteSpace: "nowrap",
    },
    "& td": {
      padding: "10px",
      borderBottom: "1px solid #EEF2F6",
      fontSize: "13px",
      lineHeight: "18px",
      verticalAlign: "top",
    },
    "& tr": {
      cursor: "pointer",
    },
    "& tr:hover td": {
      background: "var(--color-surface-subtle)",
    },
  },
  titleCell: {
    maxWidth: "340px",
    "& strong": {
      display: "block",
      fontSize: "13px",
      lineHeight: "18px",
      overflowWrap: "anywhere",
    },
    "& span": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: "12px",
      marginTop: "3px",
      overflowWrap: "anywhere",
    },
  },
  pill: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "22px",
    borderRadius: "999px",
    padding: "3px 8px",
    background: "#F2F5F8",
    color: "#445066",
    fontSize: "12px",
    fontWeight: "var(--font-weight-semibold)",
    whiteSpace: "nowrap",
  },
  high: {
    background: "rgba(224, 82, 82, 0.12)",
    color: "#BA2F2F",
  },
  medium: {
    background: "rgba(244, 161, 30, 0.16)",
    color: "#95620A",
  },
  low: {
    background: "rgba(4, 165, 132, 0.12)",
    color: "#04745E",
  },
  statusOpen: {
    background: "rgba(67, 103, 246, 0.12)",
    color: "#2548B8",
  },
  rowActions: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap",
    minWidth: "210px",
  },
  tinyButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    padding: "6px 8px",
    background: "var(--color-white)",
    color: "var(--color-text-primary)",
    fontSize: "12px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    boxShadow: "0 3px 8px rgba(15, 23, 42, 0.07)",
    textDecoration: "none",
    "&:disabled": {
      opacity: 0.5,
      cursor: "not-allowed",
    },
  },
  primaryTinyButton: {
    borderColor: "var(--color-primary)",
    background: "var(--color-primary)",
    color: "var(--color-white)",
  },
  checkbox: {
    width: "16px",
    height: "16px",
    accentColor: "var(--color-primary)",
    cursor: "pointer",
  },
  pagination: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    marginTop: "12px",
    color: "var(--color-text-muted)",
    fontSize: "13px",
    flexWrap: "wrap",
  },
  empty: {
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    background: "var(--color-white)",
    padding: "18px",
    color: "var(--color-text-muted)",
    boxShadow: "0 12px 26px rgba(15, 23, 42, 0.08)",
  },
  caseList: {
    display: "grid",
    gap: "12px",
  },
  selectAllCard: {
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    background: "var(--color-white)",
    padding: "10px 12px",
    boxShadow: "0 10px 22px rgba(15, 23, 42, 0.07)",
    "& label": {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      color: "#445066",
      fontSize: "13px",
      fontWeight: "var(--font-weight-semibold)",
    },
  },
  caseCard: {
    border: "1px solid #E1E7EF",
    borderRadius: "8px",
    background: "var(--color-white)",
    padding: "14px",
    cursor: "pointer",
    boxShadow: "0 16px 36px rgba(15, 23, 42, 0.1)",
    transition: "border-color 120ms ease, box-shadow 120ms ease, transform 120ms ease",
    "&:hover": {
      borderColor: "#B9C5D6",
      boxShadow: "0 20px 42px rgba(15, 23, 42, 0.14)",
      transform: "translateY(-1px)",
    },
  },
  caseCardSelected: {
    borderColor: "var(--color-primary)",
    boxShadow: "0 18px 40px rgba(4, 165, 132, 0.18)",
  },
  caseHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "12px",
    flexWrap: "wrap",
  },
  caseTitle: {
    display: "flex",
    gap: "10px",
    alignItems: "flex-start",
    minWidth: 0,
    flex: "1 1 360px",
    "& h2": {
      margin: 0,
      fontSize: "16px",
      lineHeight: "22px",
      overflowWrap: "anywhere",
    },
    "& p": {
      margin: [4, 0, 0, 0],
      color: "var(--color-text-muted)",
      fontSize: "12px",
      lineHeight: "18px",
      overflowWrap: "anywhere",
    },
  },
  caseBadges: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  caseBody: {
    display: "grid",
    gridTemplateColumns: "minmax(260px, 1.2fr) minmax(260px, 0.8fr)",
    gap: "12px",
    marginTop: "12px",
    "@media (max-width: 900px)": {
      gridTemplateColumns: "1fr",
    },
  },
  relationBox: {
    border: "1px solid rgba(67, 103, 246, 0.18)",
    borderRadius: "8px",
    background: "linear-gradient(180deg, var(--color-white) 0%, #F4F7FF 100%)",
    padding: "11px 12px",
    boxShadow: "0 10px 22px rgba(67, 103, 246, 0.1)",
    "& span": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: "11px",
      lineHeight: "15px",
      fontWeight: "var(--font-weight-semibold)",
      textTransform: "uppercase",
      marginBottom: "4px",
    },
    "& strong": {
      display: "block",
      color: "var(--color-text-primary)",
      fontSize: "14px",
      lineHeight: "20px",
      overflowWrap: "anywhere",
    },
    "& small": {
      display: "block",
      color: "#445066",
      fontSize: "12px",
      lineHeight: "17px",
      marginTop: "5px",
      overflowWrap: "anywhere",
    },
  },
  caseMeta: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "8px",
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
    },
    "& > div": {
      border: "1px solid #EEF2F6",
      borderRadius: "8px",
      background: "#FCFDFE",
      padding: "9px",
    },
    "& > div > span": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: "11px",
      marginBottom: "4px",
    },
    "& > div > strong": {
      display: "block",
      color: "var(--color-text-primary)",
      fontSize: "12px",
      lineHeight: "17px",
      overflowWrap: "anywhere",
    },
  },
  projectCard: {
    display: "grid",
    gridTemplateColumns: "34px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
  },
  projectCardCompact: {
    gridTemplateColumns: "34px minmax(0, 1fr)",
  },
  projectLogo: {
    width: "34px",
    height: "34px",
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    background: "var(--color-white)",
    padding: 0,
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#445066",
    fontSize: "11px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    flexShrink: 0,
    "& img": {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      display: "block",
    },
  },
  projectText: {
    minWidth: 0,
    "& small": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: "11px",
      lineHeight: "15px",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
  },
  projectName: {
    maxWidth: "100%",
    border: "none",
    background: "transparent",
    padding: 0,
    color: "var(--color-text-primary)",
    fontSize: "13px",
    lineHeight: "18px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "left",
  },
  cardActions: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    marginTop: "12px",
  },
  drawerBackdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(7, 11, 53, 0.32)",
    zIndex: 20,
  },
  drawer: {
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    width: "min(720px, 94vw)",
    background: "var(--color-white)",
    zIndex: 21,
    overflowY: "auto",
    padding: "22px",
    boxSizing: "border-box",
    boxShadow: "-16px 0 38px rgba(7, 11, 53, 0.22)",
  },
  drawerHead: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "flex-start",
    marginBottom: "14px",
    "& h2": {
      margin: [0, 0, 8, 0],
      fontSize: "20px",
      lineHeight: "26px",
      overflowWrap: "anywhere",
    },
  },
  closeButton: {
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    width: "34px",
    height: "34px",
    background: "var(--color-white)",
    cursor: "pointer",
    fontWeight: "var(--font-weight-semibold)",
    flexShrink: 0,
  },
  loadingNotice: {
    border: "1px solid rgba(67, 103, 246, 0.22)",
    borderRadius: "8px",
    background: "#F4F7FF",
    color: "#2548B8",
    padding: "9px 10px",
    marginBottom: "12px",
    fontSize: "12px",
    lineHeight: "18px",
    fontWeight: "var(--font-weight-semibold)",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "10px",
    marginBottom: "14px",
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
    },
  },
  detailItem: {
    border: "1px solid #EEF2F6",
    borderRadius: "8px",
    padding: "10px",
    background: "#FCFDFE",
    "& > span": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: "12px",
      marginBottom: "4px",
    },
    "& > strong": {
      display: "block",
      fontSize: "13px",
      lineHeight: "18px",
      overflowWrap: "anywhere",
    },
  },
  idRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  idLink: {
    border: "none",
    background: "transparent",
    padding: 0,
    color: "#2548B8",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: "13px",
    lineHeight: "18px",
    cursor: "pointer",
    textDecoration: "underline",
    overflowWrap: "anywhere",
  },
  copyButton: {
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    background: "var(--color-white)",
    color: "#445066",
    padding: "4px 7px",
    fontSize: "11px",
    fontWeight: "var(--font-weight-semibold)",
    cursor: "pointer",
  },
  idList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  section: {
    marginTop: "14px",
    "& h3": {
      margin: [0, 0, 8, 0],
      fontSize: "14px",
      lineHeight: "20px",
    },
  },
  codeBlock: {
    maxHeight: "260px",
    overflow: "auto",
    border: "1px solid #EEF2F6",
    borderRadius: "8px",
    background: "var(--color-text-primary)",
    color: "#E6EEF8",
    padding: "12px",
    fontSize: "12px",
    lineHeight: "18px",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
  candidate: {
    border: "1px solid #EEF2F6",
    borderRadius: "8px",
    background: "#FCFDFE",
    padding: "10px",
    marginBottom: "8px",
    fontSize: "12px",
    lineHeight: "18px",
    overflowWrap: "anywhere",
    boxShadow: "0 8px 18px rgba(15, 23, 42, 0.06)",
  },
  candidateGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "8px",
    "@media (max-width: 640px)": {
      gridTemplateColumns: "1fr",
    },
  },
  candidateField: {
    border: "1px solid #E6EBF1",
    borderRadius: "8px",
    background: "var(--color-white)",
    padding: "8px",
    "& span": {
      display: "block",
      color: "var(--color-text-muted)",
      fontSize: "11px",
      marginBottom: "3px",
    },
    "& strong": {
      display: "block",
      color: "var(--color-text-primary)",
      fontSize: "12px",
      lineHeight: "17px",
      overflowWrap: "anywhere",
    },
  },
  detailsBox: {
    marginTop: "8px",
    "& summary": {
      cursor: "pointer",
      color: "#2548B8",
      fontSize: "12px",
      fontWeight: "var(--font-weight-semibold)",
    },
  },
  noteBox: {
    width: "100%",
    minHeight: "82px",
    resize: "vertical",
    border: "1px solid var(--color-border)",
    borderRadius: "8px",
    padding: "10px 12px",
    boxSizing: "border-box",
    fontSize: "14px",
    lineHeight: "19px",
  },
  modal: {
    position: "fixed",
    left: "50%",
    top: "50%",
    transform: "translate(-50%, -50%)",
    width: "min(460px, 92vw)",
    borderRadius: "8px",
    background: "var(--color-white)",
    zIndex: 30,
    padding: "18px",
    boxShadow: "0 20px 40px rgba(7, 11, 53, 0.24)",
    boxSizing: "border-box",
    "& h2": {
      margin: [0, 0, 10, 0],
      fontSize: "18px",
      lineHeight: "24px",
    },
  },
});
