import { createUseStyles } from 'react-jss';

export const useStyles = createUseStyles({
  form: { display: 'flex', flexDirection: 'column', gap: 18, width: '100%' },
  intro: { color: 'var(--color-text-secondary)', fontSize: 13.5, lineHeight: '19px', marginTop: -4 },
  field: { display: 'flex', flexDirection: 'column', gap: 7 },
  label: { color: 'var(--color-text-strong)', fontSize: 13, lineHeight: '17px', fontWeight: 700 },
  input: {
    width: '100%',
    minHeight: 44,
    padding: '11px 13px',
    border: '1px solid var(--color-border)',
    borderRadius: 10,
    background: 'var(--color-white)',
    color: 'var(--color-text-primary)',
    fontSize: 14,
    lineHeight: '20px',
    boxSizing: 'border-box',
    transition: 'border-color 0.16s ease, box-shadow 0.16s ease',
    '&::placeholder': { color: 'var(--color-text-soft)' },
    '&:focus': { borderColor: 'var(--color-primary)', boxShadow: '0 0 0 3px var(--color-primary-soft)', outline: 'none' },
  },
  textarea: {
    width: '100%',
    minHeight: 84,
    padding: '11px 13px',
    border: '1px solid var(--color-border)',
    borderRadius: 10,
    background: 'var(--color-white)',
    color: 'var(--color-text-primary)',
    fontSize: 14,
    lineHeight: '20px',
    resize: 'vertical',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
    transition: 'border-color 0.16s ease, box-shadow 0.16s ease',
    '&::placeholder': { color: 'var(--color-text-soft)' },
    '&:focus': { borderColor: 'var(--color-primary)', boxShadow: '0 0 0 3px var(--color-primary-soft)', outline: 'none' },
  },
  questionsSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    paddingTop: 16,
    borderTop: '1px solid var(--color-border-subtle)',
  },
  questionsHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  questionsTitle: { fontSize: 15, fontWeight: 800, color: 'var(--color-text-primary)' },
  questionsPill: {
    display: 'inline-flex',
    marginLeft: 8,
    padding: '3px 8px',
    borderRadius: 999,
    background: 'var(--color-surface-muted)',
    color: 'var(--color-text-muted)',
    fontSize: 11,
    fontWeight: 700,
  },
  itemCard: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    padding: 15,
    paddingTop: 16,
    border: '1px solid var(--color-border)',
    borderRadius: 13,
    background: 'linear-gradient(180deg, rgba(248,250,252,0.6), rgba(255,255,255,1))',
  },
  itemHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  itemIndex: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 12.5,
    fontWeight: 800,
    color: 'var(--color-primary-dark)',
  },
  itemDot: {
    width: 22,
    height: 22,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 7,
    background: 'var(--color-primary-soft)',
    fontSize: 11.5,
  },
  removeBtn: {
    border: 'none',
    background: 'transparent',
    color: 'var(--color-danger, #dc2626)',
    fontSize: 12.5,
    fontWeight: 700,
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: 8,
    '&:hover': { background: 'rgba(220,38,38,0.08)' },
  },
  emptyItems: {
    padding: '18px 14px',
    textAlign: 'center',
    border: '1px dashed var(--color-border)',
    borderRadius: 12,
    color: 'var(--color-text-muted)',
    fontSize: 13,
  },
  addItemBtn: { alignSelf: 'flex-start' },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    paddingTop: 16,
    borderTop: '1px solid var(--color-border-subtle)',
    '@media (max-width: 480px)': { display: 'grid', gridTemplateColumns: '1fr 1fr' },
  },
  saveButton: { minWidth: 150 },
});
