/**
 * Admin/read subset of the MonolithicLaunchpad ABI supplied with the BSC
 * testnet deployment. Human-readable fragments keep the ethers v5 adapter
 * isolated from the legacy, ethers v6 connector.
 */
export const launchpadAbi = [
  "error AlreadyAdmin()",
  "error AlreadyClaimed()",
  "error AlreadyStaked()",
  "error ClaimNotEnabled()",
  "error InvalidAmount()",
  "error InvalidFeePercent()",
  "error InvalidPool()",
  "error InvalidReceiver()",
  "error MinInvestmentViolation()",
  "error NoInvestAccess()",
  "error NotAContractAdmin()",
  "error NotAdmin()",
  "error NotOwner()",
  "error NotStaked()",
  "error NotTokenOwner()",
  "error OwnershipTransferToZero()",
  "error PoolAlreadyClosed()",
  "error PoolNotClosed()",
  "error ReceiptNotFound()",
  "error RemainderTooSmall()",
  "error SafeERC20FailedOperation(address token)",
  "error StakeReleaseNotEnabled()",
  "error Unauthorized()",
  "error WrongStage()",
  "error ZeroAddress()",
  "function owner() view returns (address)",
  "function admins(address user) view returns (bool)",
  "function investmentReceiver() view returns (address)",
  "function feeReceiver() view returns (address)",
  "function stakingNft() view returns (address)",
  "function DEFAULT_MIN_INVESTMENT() view returns (uint256)",
  "function getPoolInfo(uint256 poolId) view returns (tuple(uint256 id,address investToken,uint256 targetAmount,uint256 raisedAmount,uint32 greenSeats,uint32 yellowSeats,uint64 stakeStart,uint64 greenStart,uint64 greenEnd,uint64 yellowSlotDuration,uint256 minInvestment,uint16 feePercent,address projectToken,uint256 projectTokenAmount,bool claimEnabled,bool stakeReleaseEnabled,bool closed,bool exists))",
  "function createPool(address investToken,uint256 targetAmount,uint32 greenSeats,uint32 yellowSeats,uint64 stakeStart,uint64 greenStart,uint64 greenEnd,uint64 yellowSlotDuration,uint256 minInvestment,uint16 feePercent) returns (uint256 poolId)",
  "function updatePoolFeePercent(uint256 poolId,uint16 feePercent)",
  "function updatePoolMinInvestment(uint256 poolId,uint256 newMinInvestment)",
  "function closePoolIfFinished(uint256 poolId)",
  "function depositProjectTokens(uint256 poolId,address projectToken,uint256 amount)",
  "function adminUnstakeAllPoolUsers(uint256 poolId)",
  "function addAdmin(address user)",
  "function removeAdmin(address user)",
  "function setInvestmentReceiver(address newReceiver)",
  "function setFeeReceiver(address newReceiver)",
  "function transferOwnership(address newOwner)",
  "event PoolCreated(uint256 indexed poolId,address indexed investToken,uint256 targetAmount,uint32 greenSeats,uint32 yellowSeats,uint64 stakeStart,uint64 greenStart,uint64 greenEnd,uint64 yellowSlotDuration,uint256 minInvestment,uint16 feePercent)",
  "event PoolClosed(uint256 indexed poolId,uint256 raisedAmount)",
  "event PoolFeeUpdated(uint256 indexed poolId,uint16 oldFeePercent,uint16 newFeePercent)",
  "event ProjectTokensDeposited(uint256 indexed poolId,address indexed projectToken,uint256 amount)",
] as const;

export const erc20AdminAbi = [
  "function approve(address spender,uint256 amount) returns (bool)",
  "function allowance(address owner,address spender) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function symbol() view returns (string)",
  "function balanceOf(address owner) view returns (uint256)",
  "event Approval(address indexed owner,address indexed spender,uint256 value)",
] as const;
