import { createUseStyles } from "react-jss";

const SIDEBAR_WIDTH = 264;

export const useStyles = createUseStyles({
  shell: {
    minHeight: "100vh",
    background: "var(--color-bg, #F4F7FB)",
  },
  // Mobile top bar (hidden on desktop)
  mobileBar: {
    display: "none",
    alignItems: "center",
    gap: 12,
    height: 60,
    padding: "0 16px",
    background: "var(--color-white, #fff)",
    borderBottom: "1px solid #E4EAF1",
    position: "sticky",
    top: 0,
    zIndex: 120,
    "@media (max-width: 1024px)": { display: "flex" },
    "& img": { height: 30 },
  },
  burger: {
    border: "1px solid #E4EAF1",
    background: "#fff",
    borderRadius: 8,
    width: 40,
    height: 40,
    display: "inline-flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 4,
    cursor: "pointer",
    "& span": { width: 18, height: 2, background: "#41506A", borderRadius: 2 },
  },
  overlay: {
    display: "none",
    position: "fixed",
    inset: 0,
    background: "rgba(16,24,40,0.45)",
    zIndex: 130,
    "@media (max-width: 1024px)": { display: "block" },
  },
  sidebar: {
    position: "fixed",
    top: 0,
    left: 0,
    bottom: 0,
    width: SIDEBAR_WIDTH,
    background: "var(--color-white, #fff)",
    borderRight: "1px solid #E4EAF1",
    display: "flex",
    flexDirection: "column",
    zIndex: 140,
    transition: "transform 0.22s ease",
    "@media (max-width: 1024px)": { transform: "translateX(-100%)", boxShadow: "0 12px 40px rgba(16,24,40,0.18)" },
  },
  sidebarOpen: {
    "@media (max-width: 1024px)": { transform: "translateX(0)" },
  },
  logoBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: "20px 20px 16px",
    borderBottom: "1px solid #EEF2F7",
    "& img": { height: 34 },
  },
  roleTag: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "var(--color-primary, #00C099)",
    background: "rgba(0,192,153,0.12)",
    padding: "4px 8px",
    borderRadius: 999,
  },
  nav: {
    flex: 1,
    overflowY: "auto",
    padding: "12px 12px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  navLink: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    color: "#4A5A72",
    textDecoration: "none",
    cursor: "pointer",
    border: "none",
    background: "transparent",
    width: "100%",
    textAlign: "left",
    transition: "background 0.15s ease, color 0.15s ease",
    "&:hover": { background: "#F1F5FA", color: "#1F2A3C" },
  },
  navLinkActive: {
    background: "rgba(0,192,153,0.12)",
    color: "var(--color-primary, #00C099)",
    "&:hover": { background: "rgba(0,192,153,0.16)" },
  },
  chevron: {
    display: "inline-flex",
    transition: "transform 0.18s ease",
    "& svg": { width: 12, height: 12 },
  },
  chevronOpen: { transform: "rotate(180deg)" },
  subMenu: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    margin: "2px 0 6px",
    paddingLeft: 10,
    borderLeft: "1px solid #EDF1F6",
    marginLeft: 14,
  },
  subLink: {
    display: "block",
    padding: "8px 12px",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 500,
    color: "#6B7788",
    textDecoration: "none",
    transition: "background 0.15s ease, color 0.15s ease",
    "&:hover": { background: "#F1F5FA", color: "#1F2A3C" },
  },
  subLinkActive: {
    color: "var(--color-primary, #00C099)",
    fontWeight: 700,
    background: "rgba(0,192,153,0.08)",
  },
  footer: {
    borderTop: "1px solid #EEF2F7",
    padding: 14,
    position: "relative",
  },
  userButton: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    border: "1px solid #EEF2F7",
    background: "#FBFCFE",
    borderRadius: 12,
    padding: "8px 10px",
    cursor: "pointer",
    "& img": { width: 34, height: 34, borderRadius: "50%", objectFit: "cover" },
    "&:hover": { background: "#F1F5FA" },
  },
  userMeta: { display: "flex", flexDirection: "column", flex: 1, minWidth: 0, textAlign: "left" },
  userName: { fontSize: 13, fontWeight: 700, color: "#1F2A3C", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  userRole: { fontSize: 11, color: "#8592A4", textTransform: "capitalize" },
  logoutMenu: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 64,
    background: "#fff",
    border: "1px solid #E4EAF1",
    borderRadius: 12,
    boxShadow: "0 12px 30px rgba(16,24,40,0.14)",
    padding: 8,
  },
  logoutButton: {
    width: "100%",
    border: "none",
    background: "transparent",
    padding: "10px 12px",
    borderRadius: 8,
    textAlign: "left",
    fontSize: 13.5,
    fontWeight: 600,
    color: "#C0392B",
    cursor: "pointer",
    "&:hover": { background: "rgba(226,84,84,0.08)" },
  },
  content: {
    marginLeft: SIDEBAR_WIDTH,
    minHeight: "100vh",
    transition: "margin-left 0.22s ease",
    "@media (max-width: 1024px)": { marginLeft: 0 },
  },
  // ---- Collapsed (icon rail) state ----
  sidebarCollapsed: {
    width: 76,
  },
  contentCollapsed: {
    marginLeft: 76,
    "@media (max-width: 1024px)": { marginLeft: 0 },
  },
  collapseBtn: {
    border: "1px solid #E4EAF1",
    background: "#FBFCFE",
    borderRadius: 8,
    width: 26,
    height: 26,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    color: "#4A5A72",
    flexShrink: 0,
    transition: "background 0.15s ease",
    "&:hover": { background: "#F1F5FA" },
    "& svg": { width: 12, height: 12, transition: "transform 0.18s ease" },
  },
  navInitial: {
    width: 26,
    height: 26,
    borderRadius: 8,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 800,
    background: "#F1F5FA",
    color: "#4A5A72",
    flexShrink: 0,
  },
  navInitialActive: {
    background: "rgba(0,192,153,0.14)",
    color: "var(--color-primary, #00C099)",
  },
  navIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#F1F5FA",
    color: "#4A5A72",
    flexShrink: 0,
    transition: "background 0.15s ease, color 0.15s ease",
    "& svg": { display: "block" },
  },
  navIconActive: {
    background: "rgba(0,192,153,0.14)",
    color: "var(--color-primary, #00C099)",
  },
});
