import { createUseStyles } from "react-jss";

export const useAdminDossierStyles = createUseStyles({
  wrapper: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: "0 24px",
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 12,

    "@media (max-width: 1280px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },

    "@media (max-width: 720px)": {
      gridTemplateColumns: "1fr",
    },
  },
  summaryCard: {
    background: "var(--color-white)",
    border: "1px solid rgba(83, 98, 124, 0.07)",
    boxShadow: "2px 2px 0 #EEEEEE",
    borderRadius: 8,
    padding: 16,
    minWidth: 0,
  },
  summaryTitle: {
    color: "var(--color-text-muted)",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 13,
    lineHeight: "16px",
    margin: "0 0 8px",
  },
  summaryValue: {
    color: "var(--color-text-strong)",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 22,
    lineHeight: "28px",
    margin: 0,
    wordBreak: "break-word",
  },
  summaryMeta: {
    color: "var(--color-text-secondary)",
    fontWeight: "var(--font-weight-medium)",
    fontSize: 13,
    lineHeight: "18px",
    marginTop: 6,
  },
  dossierCard: {
    background: "var(--color-white)",
    border: "1px solid rgba(83, 98, 124, 0.07)",
    boxShadow: "2px 2px 0 #EEEEEE",
    borderRadius: 8,
    minWidth: 0,
    overflow: "hidden",
  },
  tabsBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: 12,
    background: "var(--color-surface-subtle)",
    borderBottom: "1px solid rgba(83, 98, 124, 0.08)",

    "@media (max-width: 900px)": {
      alignItems: "stretch",
      flexDirection: "column",
    },
  },
  tabs: {
    display: "flex",
    alignItems: "center",
    flex: 1,
    gap: 8,
    minWidth: 0,
    overflowX: "auto",
    padding: 1,
    scrollbarWidth: "thin",
  },
  tabButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    minHeight: 38,
    border: "1px solid rgba(83, 98, 124, 0.12)",
    background: "var(--color-white)",
    color: "var(--color-text-secondary)",
    borderRadius: 8,
    boxShadow: "0 1px 2px rgba(17, 24, 39, 0.05)",
    padding: "8px 10px 8px 12px",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 13,
    lineHeight: "16px",
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "all 0.2s ease",

    "&:hover": {
      borderColor: "var(--color-primary)",
      color: "var(--color-primary)",
      boxShadow: "0 4px 12px rgba(4, 165, 132, 0.12)",
    },

    "&.active": {
      background: "var(--color-text-strong)",
      borderColor: "var(--color-text-strong)",
      color: "var(--color-white)",
      boxShadow: "0 8px 18px rgba(17, 24, 39, 0.16)",
    },

    "&.active $tabCount": {
      background: "var(--color-primary)",
      color: "var(--color-white)",
    },
  },
  tabLabel: {
    display: "inline-flex",
    alignItems: "center",
    whiteSpace: "nowrap",
  },
  tabCount: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 22,
    height: 22,
    borderRadius: 6,
    background: "rgba(83, 98, 124, 0.08)",
    color: "var(--color-text-secondary)",
    fontSize: 12,
    lineHeight: "12px",
    padding: "0 6px",
  },
  refreshButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minHeight: 38,
    border: "1px solid var(--color-primary)",
    borderRadius: 8,
    background: "var(--color-primary)",
    color: "var(--color-white)",
    boxShadow: "0 8px 18px var(--color-primary-soft-strong)",
    cursor: "pointer",
    flex: "0 0 auto",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 13,
    lineHeight: "16px",
    padding: "8px 12px",
    whiteSpace: "nowrap",

    "&:hover": {
      background: "var(--color-primary-hover)",
      borderColor: "var(--color-primary-hover)",
    },

    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.6,
    },
  },
  refreshIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 16,
    height: 16,
    fontSize: 16,
    lineHeight: "16px",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "16px 16px 8px",
  },
  sectionTitle: {
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 20,
    lineHeight: "24px",
    margin: 0,
  },
  sectionCounter: {
    color: "var(--color-text-muted)",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 13,
    lineHeight: "16px",
  },
  rows: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "0 16px 16px",
  },
  row: {
    border: "1px solid rgba(83, 98, 124, 0.08)",
    borderRadius: 8,
    padding: 12,
    minWidth: 0,
  },
  rowTop: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  rowTitle: {
    color: "var(--color-text-strong)",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 16,
    lineHeight: "21px",
    margin: 0,
    wordBreak: "break-word",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: 24,
    borderRadius: 6,
    padding: "3px 8px",
    background: "var(--color-primary-soft)",
    color: "var(--color-primary-dark)",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 12,
    lineHeight: "14px",
    whiteSpace: "nowrap",
  },
  fieldsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "10px 14px",

    "@media (max-width: 1280px)": {
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    },

    "@media (max-width: 720px)": {
      gridTemplateColumns: "1fr",
    },
  },
  field: {
    minWidth: 0,
  },
  fieldLabel: {
    display: "block",
    color: "var(--color-text-muted)",
    fontWeight: "var(--font-weight-medium)",
    fontSize: 12,
    lineHeight: "15px",
    marginBottom: 3,
  },
  fieldValue: {
    display: "block",
    color: "var(--color-text-strong)",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 14,
    lineHeight: "18px",
    wordBreak: "break-word",
  },
  textBlock: {
    color: "var(--color-text-strong)",
    fontWeight: "var(--font-weight-medium)",
    fontSize: 14,
    lineHeight: "20px",
    margin: "10px 0 0",
    wordBreak: "break-word",
  },
  terminalRows: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    margin: "0 16px 16px",
    padding: 12,
    border: "1px solid #1F1F1F",
    borderRadius: 8,
    background: "#0C0C0C",
    boxShadow: "inset 0 0 0 1px rgba(255, 255, 255, 0.03)",
    overflowX: "auto",
  },
  terminalRow: {
    minWidth: 0,
    border: "1px solid #2D2D30",
    borderLeft: "3px solid #767676",
    borderRadius: 6,
    background: "#111111",
    color: "#F2F2F2",
    fontFamily: '"Cascadia Mono", Consolas, "Courier New", monospace',
    padding: "10px 12px",
  },
  terminalCommandLine: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    minWidth: 0,
  },
  terminalPrompt: {
    color: "#569CD6",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 13,
    lineHeight: "18px",
    whiteSpace: "nowrap",
  },
  terminalCommand: {
    color: "var(--color-white)",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 13,
    lineHeight: "18px",
    minWidth: 0,
    wordBreak: "break-word",
  },
  terminalStatus: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: 22,
    border: "1px solid rgba(255, 255, 255, 0.12)",
    borderRadius: 5,
    color: "#D4D4D4",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 11,
    lineHeight: "14px",
    padding: "2px 6px",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  terminalTitle: {
    color: "var(--color-white)",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 14,
    lineHeight: "20px",
    margin: "8px 0 0",
    wordBreak: "break-word",
  },
  terminalMetaGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "4px 14px",
    color: "#C8C8C8",
    fontSize: 12,
    fontWeight: "var(--font-weight-medium)",
    lineHeight: "17px",
    marginTop: 8,

    "& span": {
      minWidth: 0,
      wordBreak: "break-word",
    },

    "@media (max-width: 720px)": {
      gridTemplateColumns: "1fr",
    },
  },
  terminalPayload: {
    borderTop: "1px solid rgba(255, 255, 255, 0.08)",
    color: "#D4D4D4",
    fontFamily: "inherit",
    fontSize: 12,
    lineHeight: "18px",
    margin: "10px 0 0",
    maxHeight: 180,
    overflow: "auto",
    paddingTop: 10,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  terminalSuccess: {
    borderLeftColor: "#16C60C",

    "& $terminalStatus": {
      background: "rgba(22, 198, 12, 0.12)",
      borderColor: "rgba(22, 198, 12, 0.36)",
      color: "#16C60C",
    },
  },
  terminalError: {
    borderLeftColor: "#F14C4C",

    "& $terminalStatus": {
      background: "rgba(241, 76, 76, 0.12)",
      borderColor: "rgba(241, 76, 76, 0.36)",
      color: "#F14C4C",
    },
  },
  terminalWarning: {
    borderLeftColor: "#F9F1A5",

    "& $terminalStatus": {
      background: "rgba(249, 241, 165, 0.12)",
      borderColor: "rgba(249, 241, 165, 0.36)",
      color: "#F9F1A5",
    },
  },
  empty: {
    color: "var(--color-text-muted)",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 14,
    lineHeight: "18px",
    padding: "8px 16px 20px",
  },
  footer: {
    display: "flex",
    justifyContent: "center",
    padding: "0 16px 16px",
  },
  loadMoreButton: {
    border: "1px solid var(--color-primary)",
    background: "var(--color-white)",
    color: "var(--color-primary)",
    borderRadius: 8,
    padding: "8px 14px",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 14,
    lineHeight: "18px",
    cursor: "pointer",

    "&:hover": {
      background: "var(--color-primary)",
      color: "var(--color-white)",
    },

    "&:disabled": {
      cursor: "not-allowed",
      opacity: 0.6,
    },
  },
  error: {
    color: "var(--color-danger)",
    fontWeight: "var(--font-weight-semibold)",
    fontSize: 14,
    lineHeight: "18px",
    padding: "8px 16px 20px",
  },
});
