import { Module } from "@nestjs/common";
import { ConfigModule, ConfigService } from "@nestjs/config";
import { JwtModule } from "@nestjs/jwt";
import { MongooseModule } from "@nestjs/mongoose";
import { EntitlementsModule } from "src/entitlements/entitlements.module";
import { NestjsFormDataModule } from "nestjs-form-data";
import { CoinGeckoMarketUpdateService } from "src/coingecko/coingecko-market-update.service";
import { CoinGeckoProClientService } from "src/coingecko/coingecko-pro-client.service";
import {
  assertParserMongoConfiguration,
  buildParserMongoUri,
} from "src/config/mongo.config";
import { FilesService } from "src/files/files.service";
import { ExternalAssetMirrorUrlService } from "src/storage/external-asset-mirror-url.service";
import { ExternalAssetMirrorWriteService } from "src/storage/external-asset-mirror-write.service";
import { SpaceportNftModule } from "src/spaceport-nft/spaceport-nft.module";
import { StorageModule } from "src/storage/storage.module";
import {
  FOMO_V2_ACTIVITY_ENTITLEMENT_RESOLVER,
  FOMO_V2_ACTIVITY_USER_STATE_RESOLVER,
} from "./domains/activities";
import { FomoV2ActivityUserStateService } from "src/crypto-activities/services/fomo-v2-activity-user-state.service";
import { FomoV2ActivitiesAdminController } from "./domains/activities/controllers/activities-admin.controller";
import { EarlyLandAccessAdminController } from "./domains/activities/controllers/earlyland-access-admin.controller";
import {
  EarlyLandAccessSettings,
  EarlyLandAccessSettingsSchema,
  EarlyLandAccessGrant,
  EarlyLandAccessGrantSchema,
} from "./domains/activities/models/earlyland-access.model";
import { User, UserSchema } from "src/user/user.model";
import { FomoV2ActivitiesController } from "./domains/activities/controllers/activities.controller";
import { FomoV2SpaceportActivityEntitlementService } from "./integrations/spaceport-activity-entitlement.service";
import { FomoV2BackersAdminController } from "./domains/backers/controllers/backers-admin.controller";
import { FomoV2BackersController } from "./domains/backers/controllers/backers.controller";
import { FomoV2FundingFeedController } from "./domains/funding/controllers/funding-feed.controller";
import { FomoV2FundingRoundsCompatibilityController } from "./domains/funding/controllers/funding-rounds-compatibility.controller";
import { InternalSyncGuard } from "src/common/guards/internal-sync.guard";
import { FomoV2EntityFlagService } from "./domains/flags";
import { FomoV2EntityFlagsController } from "./domains/flags/controllers";
import { FOMO_V2_PARSER_DB_CONNECTION } from "./domains/ico";
import { FomoV2IcoProjectsController } from "./domains/ico/controllers/ico-projects.controller";
import {
  FomoV2LaunchpadAdminController,
  FomoV2LaunchpadAdminService,
  FomoV2LaunchpadChainService,
  FomoV2LaunchpadDeploymentService,
  FomoV2LaunchpadPlacementAdminController,
  FomoV2LaunchpadPlacementController,
  FomoV2LaunchpadPlacementService,
  FomoV2LaunchpadPublicController,
  FomoV2LaunchpadPublicService,
  FomoV2LaunchpadSyncService,
} from "./domains/launchpad";
import { FomoV2MarketAdminController } from "./domains/market/controllers/market-admin.controller";
import { FomoV2MarketProjectsController } from "./domains/market/controllers/market-projects.controller";
import { FomoV2ProjectExchangeMarketsController } from "./domains/market/controllers/project-exchange-markets.controller";
import {
  FomoV2ParserControlAdminController,
  FomoV2UpstreamParserAdminController,
  FomoV2ParserControlPolicyModule,
  FomoV2ParserControlRegistryService,
  FomoV2PostWriteMaterializationService,
  FomoV2ParserSnapshotReaderService,
  FomoV2ParserControlService,
  FomoV2ParserControlWorkerService,
  FomoV2UpstreamParserOrchestrationService,
  IntelParserControlClient,
} from "./domains/parser-control";
import { FomoV2ReviewCaseAdminController } from "./domains/review/controllers/review-case-admin.controller";
import { FomoV2EntityReactionService } from "./domains/reactions";
import { FomoV2EntityReactionsController } from "./domains/reactions/controllers";
import { FomoV2TabsController } from "./domains/tabs/controllers";
import { FomoV2TabsService } from "./domains/tabs/services";
import { FomoV2UnlockActionsController } from "./domains/unlocks/controllers/unlock-actions.controller";
import { FomoV2UnlockFeedController } from "./domains/unlocks/controllers/unlock-feed.controller";
import {
  FomoV2PersistenceModule,
  FOMO_V2_PARSER_REGISTRATION_MODEL_DEFINITIONS,
} from "./persistence";
import {
  FomoV2CoinGeckoMarketHistorySyncService,
  FomoV2ActivityAccessPolicyService,
  EarlyLandAccessAdminService,
  FomoV2ActivityAdminService,
  FomoV2ActivityAiReviewService,
  FomoV2ActivityCanonicalReviewService,
  FomoV2ActivityIngestService,
  FomoV2ActivityOptionalJwtGuard,
  FomoV2ActivityPublicReadService,
  FomoV2ActivitySourceImportService,
  FomoV2ActivitySourceSplitRemediationService,
  FomoV2BackerProfileImportService,
  FomoV2BackerPortfolioRebuildService,
  FomoV2BackerListReadModelService,
  FomoV2BackerReadService,
  FomoV2BackerService,
  FomoV2CanonicalProjectRatingRebuildService,
  FomoV2DomainIntegrityAuditService,
  FomoV2FundingImportDryRunService,
  FomoV2FundingFeedReadService,
  FomoV2FundingFeedReadModelService,
  FomoV2IcodropsFundingFallbackImportService,
  FomoV2IntelFundraisingGapFillDryRunService,
  FomoV2FundingService,
  FomoV2ImportCandidateService,
  FomoV2UnlockEventApplyService,
  FomoV2UnlockActionsService,
  FomoV2UnlockEventsImportService,
  FomoV2UnlockFeedReadService,
  FomoV2UnlocksService,
  FomoV2VestingAllocationScheduleImportService,
  FomoV2VestingCandidateNormalizerService,
  FomoV2VestingDedupeService,
  FomoV2VestingLinkingService,
  FomoV2VestingImportService,
  FomoV2VestingReviewApplyService,
  FomoV2VestingSourceReaderService,
  FomoV2VestingSourceSnapshotSyncService,
  FomoV2VestingService,
  IcoProjectProfileAuditService,
  IcoProjectProfileImportService,
  IcoProjectScreenshotsBackfillService,
  FomoV2IcoProjectComparisonReadService,
  FomoV2IcoProjectReadService,
  IcoProjectResolverService,
  FomoV2IndexService,
  FomoV2MarketHistoryImportAdminService,
  FomoV2MarketProjectChartReadService,
  FomoV2MarketProjectChartImageService,
  FomoV2MarketProjectDataUpdateService,
  FomoV2MarketProjectDetailSyncService,
  FomoV2MarketProjectPerformanceService,
  FomoV2MarketProjectReadModelService,
  FomoV2MarketProjectRoiMetricService,
  FomoV2MarketSyncStateService,
  FomoV2MarketSyncScheduleRebaseService,
  FomoV2MarketProjectTokenComparisonService,
  FomoV2MigrationRunWriterService,
  FomoV2ProjectExchangeMarketsService,
  FomoV2ProjectPerformanceSyncService,
  FomoV2ProjectDomainSourceService,
  FomoV2ParserImportRuntimeService,
  FomoV2ReviewCaseAdminService,
  FomoV2ReviewService,
  ResolveCanonicalProjectService,
} from "./services";

@Module({
  imports: [
    ConfigModule,
    JwtModule.register({}),
    EntitlementsModule,
    SpaceportNftModule,
    StorageModule,
    NestjsFormDataModule,
    MongooseModule.forRootAsync({
      connectionName: FOMO_V2_PARSER_DB_CONNECTION,
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => {
        const parserMongoEnv = {
          NODE_ENV: configService.get<string>("NODE_ENV"),
          DB_URL: configService.get<string>("DB_URL"),
          MONGO_URL: configService.get<string>("MONGO_URL"),
          MONGODB_URI: configService.get<string>("MONGODB_URI"),
          DB_NAME: configService.get<string>("DB_NAME"),
          DB_PARSER_URI: configService.get<string>("DB_PARSER_URI"),
          DB_PARSER_NAME: configService.get<string>("DB_PARSER_NAME"),
        } as NodeJS.ProcessEnv;
        assertParserMongoConfiguration(parserMongoEnv);

        return {
          uri: buildParserMongoUri(parserMongoEnv),
          maxPoolSize: parseInt(
            configService.get<string>("DB_PARSER_MAX_POOL_SIZE") ||
              configService.get<string>("DB_MAX_POOL_SIZE") ||
              "5",
            10
          ),
          minPoolSize: parseInt(
            configService.get<string>("DB_PARSER_MIN_POOL_SIZE") || "0",
            10
          ),
          autoIndex: false,
        };
      },
    }),
    FomoV2PersistenceModule,
    FomoV2ParserControlPolicyModule,
    MongooseModule.forFeature([
      { name: EarlyLandAccessSettings.name, schema: EarlyLandAccessSettingsSchema },
      { name: EarlyLandAccessGrant.name, schema: EarlyLandAccessGrantSchema },
      { name: User.name, schema: UserSchema },
    ]),
    MongooseModule.forFeature(
      [...FOMO_V2_PARSER_REGISTRATION_MODEL_DEFINITIONS],
      FOMO_V2_PARSER_DB_CONNECTION
    ),
  ],
  controllers: [
    FomoV2ProjectExchangeMarketsController,
    FomoV2MarketProjectsController,
    FomoV2ActivitiesController,
    FomoV2ActivitiesAdminController,
    EarlyLandAccessAdminController,
    FomoV2MarketAdminController,
    FomoV2LaunchpadAdminController,
    FomoV2LaunchpadPlacementAdminController,
    FomoV2LaunchpadPlacementController,
    FomoV2LaunchpadPublicController,
    FomoV2FundingFeedController,
    FomoV2FundingRoundsCompatibilityController,
    FomoV2BackersController,
    FomoV2BackersAdminController,
    FomoV2IcoProjectsController,
    FomoV2UnlockActionsController,
    FomoV2UnlockFeedController,
    FomoV2ReviewCaseAdminController,
    FomoV2EntityReactionsController,
    FomoV2EntityFlagsController,
    FomoV2TabsController,
    FomoV2ParserControlAdminController,
    FomoV2UpstreamParserAdminController,
  ],
  providers: [
    ResolveCanonicalProjectService,
    FomoV2ActivityAccessPolicyService,
    FomoV2ActivityAdminService,
    FomoV2ActivityAiReviewService,
    FomoV2ActivityCanonicalReviewService,
    FomoV2ActivityIngestService,
    FomoV2ActivityOptionalJwtGuard,
    FomoV2ActivityPublicReadService,
    EarlyLandAccessAdminService,
    FomoV2ActivitySourceImportService,
    FomoV2ActivitySourceSplitRemediationService,
    FomoV2ParserImportRuntimeService,
    FomoV2ParserControlRegistryService,
    FomoV2PostWriteMaterializationService,
    FomoV2ParserSnapshotReaderService,
    FomoV2ParserControlService,
    FomoV2ParserControlWorkerService,
    FomoV2UpstreamParserOrchestrationService,
    IntelParserControlClient,
    FomoV2SpaceportActivityEntitlementService,
    {
      provide: FOMO_V2_ACTIVITY_ENTITLEMENT_RESOLVER,
      useExisting: FomoV2SpaceportActivityEntitlementService,
    },
    FomoV2ActivityUserStateService,
    {
      provide: FOMO_V2_ACTIVITY_USER_STATE_RESOLVER,
      useExisting: FomoV2ActivityUserStateService,
    },
    FomoV2MigrationRunWriterService,
    FomoV2LaunchpadDeploymentService,
    FomoV2LaunchpadChainService,
    FomoV2LaunchpadAdminService,
    FomoV2LaunchpadPlacementService,
    FomoV2LaunchpadSyncService,
    FomoV2LaunchpadPublicService,
    FomoV2IndexService,
    FomoV2DomainIntegrityAuditService,
    FomoV2CoinGeckoMarketHistorySyncService,
    FomoV2MarketHistoryImportAdminService,
    CoinGeckoProClientService,
    CoinGeckoMarketUpdateService,
    FomoV2MarketProjectReadModelService,
    FomoV2MarketProjectChartReadService,
    FomoV2MarketProjectChartImageService,
    FomoV2MarketProjectDataUpdateService,
    FomoV2MarketProjectDetailSyncService,
    ExternalAssetMirrorUrlService,
    ExternalAssetMirrorWriteService,
    FilesService,
    FomoV2MarketProjectPerformanceService,
    FomoV2MarketProjectRoiMetricService,
    FomoV2MarketSyncStateService,
    FomoV2MarketSyncScheduleRebaseService,
    FomoV2MarketProjectTokenComparisonService,
    FomoV2ProjectExchangeMarketsService,
    FomoV2ProjectPerformanceSyncService,
    FomoV2ProjectDomainSourceService,
    FomoV2ReviewCaseAdminService,
    FomoV2ReviewService,
    FomoV2EntityReactionService,
    FomoV2EntityFlagService,
    FomoV2TabsService,
    FomoV2BackerService,
    FomoV2CanonicalProjectRatingRebuildService,
    FomoV2BackerProfileImportService,
    FomoV2BackerPortfolioRebuildService,
    FomoV2BackerListReadModelService,
    FomoV2BackerReadService,
    FomoV2FundingFeedReadService,
    InternalSyncGuard,
    FomoV2FundingFeedReadModelService,
    FomoV2FundingImportDryRunService,
    FomoV2IcodropsFundingFallbackImportService,
    FomoV2IntelFundraisingGapFillDryRunService,
    FomoV2FundingService,
    FomoV2VestingService,
    FomoV2VestingSourceReaderService,
    FomoV2VestingLinkingService,
    FomoV2VestingSourceSnapshotSyncService,
    FomoV2VestingCandidateNormalizerService,
    FomoV2VestingDedupeService,
    FomoV2VestingAllocationScheduleImportService,
    FomoV2VestingImportService,
    FomoV2VestingReviewApplyService,
    FomoV2UnlockEventApplyService,
    FomoV2UnlockActionsService,
    FomoV2UnlockEventsImportService,
    FomoV2UnlockFeedReadService,
    FomoV2UnlocksService,
    FomoV2ImportCandidateService,
    IcoProjectResolverService,
    IcoProjectProfileImportService,
    IcoProjectProfileAuditService,
    IcoProjectScreenshotsBackfillService,
    FomoV2IcoProjectComparisonReadService,
    FomoV2IcoProjectReadService,
  ],
  exports: [
    MongooseModule,
    FomoV2PersistenceModule,
    ResolveCanonicalProjectService,
    FomoV2ActivityAccessPolicyService,
    FomoV2ActivityAdminService,
    FomoV2ActivityAiReviewService,
    FomoV2ActivityCanonicalReviewService,
    FomoV2ActivityIngestService,
    FomoV2ActivityOptionalJwtGuard,
    FomoV2ActivityPublicReadService,
    FomoV2ActivitySourceImportService,
    FomoV2ActivitySourceSplitRemediationService,
    FomoV2ParserImportRuntimeService,
    FomoV2PostWriteMaterializationService,
    FomoV2ParserControlService,
    FomoV2ParserControlPolicyModule,
    FomoV2ActivityUserStateService,
    FomoV2MigrationRunWriterService,
    FomoV2LaunchpadDeploymentService,
    FomoV2LaunchpadChainService,
    FomoV2LaunchpadAdminService,
    FomoV2LaunchpadPlacementService,
    FomoV2LaunchpadSyncService,
    FomoV2LaunchpadPublicService,
    FomoV2IndexService,
    FomoV2DomainIntegrityAuditService,
    FomoV2CoinGeckoMarketHistorySyncService,
    FomoV2MarketHistoryImportAdminService,
    FomoV2MarketProjectReadModelService,
    FomoV2MarketProjectChartReadService,
    FomoV2MarketProjectChartImageService,
    FomoV2MarketProjectDataUpdateService,
    FomoV2MarketProjectDetailSyncService,
    FomoV2MarketProjectPerformanceService,
    FomoV2MarketProjectRoiMetricService,
    FomoV2MarketSyncStateService,
    FomoV2MarketSyncScheduleRebaseService,
    FomoV2MarketProjectTokenComparisonService,
    FomoV2ProjectExchangeMarketsService,
    FomoV2ProjectPerformanceSyncService,
    FomoV2ProjectDomainSourceService,
    FomoV2ReviewCaseAdminService,
    FomoV2ReviewService,
    FomoV2EntityReactionService,
    FomoV2EntityFlagService,
    FomoV2TabsService,
    FomoV2BackerService,
    FomoV2CanonicalProjectRatingRebuildService,
    FomoV2BackerProfileImportService,
    FomoV2BackerPortfolioRebuildService,
    FomoV2BackerListReadModelService,
    FomoV2BackerReadService,
    FomoV2FundingFeedReadService,
    FomoV2FundingImportDryRunService,
    FomoV2IcodropsFundingFallbackImportService,
    FomoV2IntelFundraisingGapFillDryRunService,
    FomoV2FundingService,
    FomoV2VestingService,
    FomoV2VestingSourceReaderService,
    FomoV2VestingLinkingService,
    FomoV2VestingSourceSnapshotSyncService,
    FomoV2VestingCandidateNormalizerService,
    FomoV2VestingDedupeService,
    FomoV2VestingAllocationScheduleImportService,
    FomoV2VestingImportService,
    FomoV2VestingReviewApplyService,
    FomoV2UnlockEventApplyService,
    FomoV2UnlockActionsService,
    FomoV2UnlockEventsImportService,
    FomoV2UnlockFeedReadService,
    FomoV2UnlocksService,
    FomoV2ImportCandidateService,
    IcoProjectResolverService,
    IcoProjectProfileImportService,
    IcoProjectProfileAuditService,
    IcoProjectScreenshotsBackfillService,
    FomoV2IcoProjectComparisonReadService,
    FomoV2IcoProjectReadService,
  ],
})
export class FomoV2Module {}
