import { createUseStyles } from 'react-jss';

export const useStyles = createUseStyles({
  page: {
    width: 'calc(100% - 48px)',
    maxWidth: 1366,
    margin: '24px auto 64px',
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
    '@media (max-width: 720px)': {
      width: 'calc(100% - 24px)',
      marginTop: 16,
    },
  },
  hero: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 24,
    padding: '25px 28px',
    overflow: 'hidden',
    borderRadius: 20,
    background: 'linear-gradient(120deg, #071b21 0%, #063b34 58%, #057f69 100%)',
    boxShadow: '0 22px 48px rgba(7, 27, 33, 0.16)',
    '& *': { color: 'var(--color-white)' },
    '@media (max-width: 720px)': {
      alignItems: 'flex-start',
      flexDirection: 'column',
      padding: 22,
      borderRadius: 16,
    },
  },
  eyebrow: {
    marginBottom: 7,
    color: '#8ff4d8 !important',
    fontSize: 11,
    lineHeight: '15px',
    fontWeight: 700,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  title: { fontSize: 31, lineHeight: '37px', letterSpacing: '-0.02em' },
  heroDescription: {
    maxWidth: 720,
    marginTop: 8,
    color: 'rgba(255, 255, 255, 0.74) !important',
    fontSize: 14,
    lineHeight: '21px',
  },
  countBadge: {
    flexShrink: 0,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 36,
    padding: '8px 14px',
    border: '1px solid rgba(255, 255, 255, 0.18)',
    borderRadius: 999,
    background: 'rgba(255, 255, 255, 0.1)',
    fontSize: 12,
    lineHeight: '16px',
    fontWeight: 600,
  },
  badgeDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: '#67e8b8',
    boxShadow: '0 0 0 4px rgba(103, 232, 184, 0.14)',
  },
  panel: {
    overflow: 'hidden',
    border: '1px solid rgba(83, 98, 124, 0.13)',
    borderRadius: 18,
    background: 'var(--color-white)',
    boxShadow: '0 14px 36px rgba(7, 11, 53, 0.055)',
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    padding: '18px 22px',
    borderBottom: '1px solid var(--color-border-subtle)',
    background: 'linear-gradient(180deg, rgba(248, 250, 252, 0.94), rgba(255, 255, 255, 0.9))',
    '@media (max-width: 600px)': { flexDirection: 'column', alignItems: 'stretch', padding: 18 },
  },
  panelHeaderText: { display: 'flex', flexDirection: 'column', gap: 5 },
  panelTitleRow: { display: 'flex', alignItems: 'center', gap: 10 },
  panelTitle: { fontSize: 19, lineHeight: '24px', color: 'var(--color-text-primary)' },
  panelPill: {
    display: 'inline-flex',
    padding: '4px 9px',
    borderRadius: 999,
    background: 'var(--color-primary-soft)',
    color: 'var(--color-primary-dark)',
    fontSize: 11,
    lineHeight: '14px',
    fontWeight: 700,
  },
  panelDescription: {
    maxWidth: 780,
    color: 'var(--color-text-secondary)',
    fontSize: 14,
    lineHeight: '20px',
  },
  addButton: { minWidth: 168, whiteSpace: 'nowrap' },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 14,
    padding: 20,
    '@media (max-width: 820px)': { gridTemplateColumns: '1fr', padding: 14 },
  },
  card: {
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 13,
    padding: 17,
    border: '1px solid var(--color-border)',
    borderRadius: 14,
    background: 'var(--color-white)',
    transition: 'border-color 0.16s ease, box-shadow 0.16s ease, transform 0.16s ease',
    '&:hover': {
      borderColor: 'rgba(4, 165, 132, 0.28)',
      boxShadow: '0 12px 26px rgba(7, 11, 53, 0.07)',
      transform: 'translateY(-1px)',
    },
  },
  cardTop: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  icon: {
    width: 38,
    height: 38,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    background: 'var(--color-primary-soft)',
    color: 'var(--color-primary-dark)',
    fontSize: 17,
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  statusPill: {
    padding: '5px 8px',
    borderRadius: 999,
    background: 'var(--color-primary-soft)',
    color: 'var(--color-primary-dark)',
    fontSize: 11,
    lineHeight: '14px',
    fontWeight: 700,
  },
  emptyStatus: { background: 'var(--color-warning-soft)', color: 'var(--color-warning-dark)' },
  cardTitle: { fontSize: 17, lineHeight: '22px', color: 'var(--color-text-primary)', wordBreak: 'break-word' },
  cardDescription: {
    marginTop: 4,
    color: 'var(--color-text-secondary)',
    fontSize: 13,
    lineHeight: '18px',
    wordBreak: 'break-word',
  },
  excerpt: { minHeight: 40, color: 'var(--color-text-muted)', fontSize: 13, lineHeight: '20px' },
  emptyExcerpt: { fontStyle: 'italic' },
  cardFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 'auto',
    paddingTop: 12,
    borderTop: '1px solid var(--color-border-subtle)',
    '@media (max-width: 480px)': { alignItems: 'stretch', flexDirection: 'column' },
  },
  cardMeta: { color: 'var(--color-text-soft)', fontSize: 11, lineHeight: '15px' },
  cardActions: { display: 'flex', gap: 8, flexShrink: 0 },
  editButton: { minWidth: 82, padding: '9px 12px !important' },
  deleteButton: {
    minWidth: 82,
    padding: '9px 12px !important',
    color: 'var(--color-danger, #dc2626) !important',
    borderColor: 'rgba(220, 38, 38, 0.35) !important',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
    padding: '48px 24px',
    textAlign: 'center',
  },
  emptyTitle: { fontSize: 16, fontWeight: 700, color: 'var(--color-text-primary)' },
  emptyText: { fontSize: 13.5, color: 'var(--color-text-secondary)', maxWidth: 420 },
});
